### ISSUE TITLE
Error in GWT compile mode

### ISSUE THREAD

**Issue by sriharshachilakapati** [JOML-CI/JOML#100]
I started to port the examples of WebGL4J to use JOML. Unfortunately I'm greeted with an error message:

~~~
:examples:compileGwt                 
Jan 06, 2017 8:55:28 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Compiling module com.shc.webgl4j.examples.client
   [ERROR] Errors in 'org/joml/Options.java'
      [ERROR] Line 59: Only string constants may be used as property name in System.getProperty()
:examples:compileGwt FAILED
~~~

The reason is that `System.getProperty` calls are inlined by the compiler so they must have constant args. Think of it like a `GWT.create` call with a String.

Better solution will be to replace `hasOption` calls with a regex to `System.getProperty()`.

~~~
hasOption\((.+)\)
Boolean.parseBoolean(System.getProperty($1));
~~~

That is sufficient in my opinion. By the way, the use of pre-processor is a nice idea, does that work with IDE support? I don't think it works in IDE, but am curious.

**Comment by httpdigest** [comment]
I tried calling System.getProperty() with a string literal argument, but then the GWT compiler complained about it not knowing about that particular property (such as "joml.debug").
Do you know how it is possible to pass system properties to the GWT compiler at build-time and at the same time provide defaults when those properties are not provided by the user at build-time?

**Comment by sriharshachilakapati** [comment]
You have to define the properties that you use in the module description file, and also set the accepted values.

~~~xml
<define-property name="joml.debug" values="true,false">
~~~

Then whenever we want to set the property in the user project, they would add the set property command to their module file like

~~~xml
<set-property name="joml.debug" value="true">
~~~
