### ISSUE TITLE
Matrix 3x2 and Android

### ISSUE THREAD

**Issue by TheMrButcher** [JOML-CI/JOML#103]
Hi!

I'm developing small Android 2D game using OpenGL ES 2.0. So I need math library that provides 2D-vectors and 2D-transformations. And this library is what I need but there is one problem... Matrix3x2 was added in the last release 1.9.2. But there is no such release for Android. The last one is 1.9.1. It would be great if you port 1.9.2 release to Android.

Anyway, thanks for your work.

**Comment by httpdigest** [comment]
Added with https://github.com/JOML-CI/JOML/commit/7e0bd1dc612b25b2f6c02083e069ad282961acac

**Comment by httpdigest** [comment]
Please note that the current/latest version of org.joml:joml-android is now 1.9.3-SNAPSHOT, just like the desktop/JRE variant.
