### ISSUE TITLE
Rotate about a pre-transformed axis

### ISSUE THREAD

**Issue by Immueggpain** [JOML-CI/JOML#104]
Hi, I want my camera to rotate about the pre-transformed y-axis, which is the world's y-axis not the camera's local one. I do it like this:
```
camera.invert(cameraInv);
camera.rotate(rotspeed, new Vector3f(0, 1, 0).mulDirection(cameraInv.setTranslation(0, 0, 0)));
```
I first convert the y-axis with the invert of the camera matrix to camera space, then rotate about it.
I am wondering if I'm doing something wrong and there is some convenient way to achieve this?

**Comment by httpdigest** [comment]
There is a shorter and much faster way to do this, yes:
```Java
camera.rotate(rotspeed, camera.positiveY(new Vector3f()));
```

**Comment by httpdigest** [comment]
We need to be precise, though, what exactly we mean when saying _rotating around the world's +Y axis_. Your code and the shorter version I posted above have another effect.
Given a camera view matrix, that is, the transformation transforming from world-space to view-space, then our both methods rotate the camera around its local +Y axis with the world's origin being the rotation pivot point.
If you want to indeed rotate the camera around the world's +Y axis with the world origin being the pivot point, then a simple `m.rotateY(...)` (with `m` being the world-space -> view-space transformation) does exactly that. So, no need to invert anything here.

**Comment by Immueggpain** [comment]
@httpdigest Thanks for the faster version. Exactly what I need!
 I was wrong about saying the _world's +Y axis_ because I may have misunderstood the definition of transformation matrix. I believe the real transformation matrix is `cameraInv`. So when you say _rotate the camera around its local +Y axis with the world's origin_, it actually means _rotate the camera around world's +Y axis with the camera's origin_ in my way.
And I'm gonna put some code here to illustrate this.
The world's Z+ axis means upward.
```
// init
       public Matrix4f project = new Matrix4f().perspective(FOV, 1, Z_NEAR, Z_FAR);
       public Matrix4f camera = new Matrix4f().translate(0, -5, 3).rotateX((float) Math.toRadians(90));
       private static final Quaternionf forward_roll_90 = new Quaternionf(
			new AxisAngle4f((float) Math.toRadians(-90), new Vector3f(1, 0, 0)));
// render
		float speed = 0.05f;
		float rotspeed = 0.03f;

		Vector3f up = camera.positiveZ(new Vector3f());
		up.rotate(forward_roll_90, horizontal_forward);

		// lock upward and WSAD moves horizontally
		if (window.isKeyPressed(GLFW_KEY_W)) {
			horizontal_forward.normalize();
			horizontal_forward.mul(speed);
			camera.translate(horizontal_forward);
		} else if (window.isKeyPressed(GLFW_KEY_S)) {
			horizontal_forward.normalize();
			horizontal_forward.mul(-speed);
			camera.translate(horizontal_forward);
		}
		if (window.isKeyPressed(GLFW_KEY_A)) {
			camera.translate(-speed, 0, 0);
		} else if (window.isKeyPressed(GLFW_KEY_D)) {
			camera.translate(speed, 0, 0);
		}
		if (window.isKeyPressed(GLFW_KEY_SPACE)) { // raise
			camera.translate(0, speed, 0);
		} else if (window.isKeyPressed(GLFW_KEY_LEFT_SHIFT)) { // lower
			camera.translate(0, -speed, 0);
		}
		if (window.isKeyPressed(GLFW_KEY_UP)) {
			camera.rotateX(rotspeed);
		} else if (window.isKeyPressed(GLFW_KEY_DOWN)) {
			camera.rotateX(-rotspeed);
		}
		if (window.isKeyPressed(GLFW_KEY_LEFT)) {
			camera.rotate(rotspeed, up);
		} else if (window.isKeyPressed(GLFW_KEY_RIGHT)) {
			camera.rotate(-rotspeed, up);
		}

		camera.invert(cameraInv);
		transform.identity();
		transform.mul(project);
		transform.mul(cameraInv);

// shader
     gl_Position = transform*position;
```
As you can see, I'm using the invert of `camera` to transform the vertices. Because in this way, it would be more intuitive to move the camera. For example, `camera.translate(-speed, 0, 0)` simply means move left, as -X is left in camera's space.

**Comment by Immueggpain** [comment]
Also I'm wondering if JOML already offers such methods to achieve this on camera view matrix(V), so that I won't need to invert the V and do it myself?

**Comment by httpdigest** [comment]
Okay, I see. If you want to rotate around the local camera axes (the view-space axes) and use the view-space origin (i.e. the camera's position) as rotation pivot point, use either:
- `Matrix4f.rotateLocal` (either with axis-angle or quaternion); or
- use Quaternionf.integrate()/rotateLocal() and build the view transformation from updated position and rotation

For the latter option, see this class: https://github.com/JOML-CI/joml-camera/blob/master/src/org/joml/camera/FreeCamera.java#L54
