### ISSUE TITLE
Does not support heap array backed FloatBuffer?

### ISSUE THREAD

**Issue by Immueggpain** [JOML-CI/JOML#105]
Run the code below and my app crashed. It seems that JOML doesn't support array backed FloatBuffer?
```
FloatBuffer fb = FloatBuffer.allocate(16);
new Matrix4f().get(fb);
```

**Comment by httpdigest** [comment]
JOML does support NIO buffers backed by heap arrays with a JVM system parameter.
See:
- https://github.com/JOML-CI/JOML/wiki/Configuration

The rationale behind this is explained here:
- https://github.com/JOML-CI/JOML/wiki/Design#java-nio-buffers

**Comment by Immueggpain** [comment]
OK, I see. But I do use NIO buffers a lot with heap arrays, especially the `duplicate()` methods. 
Hmmmm, I guess I can wrap the get(float[]) method to make an indirect FloatBuffer version.

**Comment by Immueggpain** [comment]
Thanks for the reply. I'm closing the issue.
