### ISSUE TITLE
Node Object with  QuadTree , Octree getting objects around camera ( Frustum Culling)

### ISSUE THREAD

**Issue by jduke32** [JOML-CI/JOML#107]
Hi , there is no java source util for 
Scene management for OpenGL
Quadtree Frustum culling
here is youtube animation:
https://www.youtube.com/watch?v=5y2x2KkwRAI&t=76s
it would be good if any utils on JOML

**Comment by httpdigest** [comment]
The reason why this is not in JOML and likely never will be, is that there are a myriad of possible ways people would want such a quadtree/octree implementation to behave and integrate into their game/engine.
There is however the basic building block of testing frusta against a axis-aligned box in the FrustumIntersection class.
You could easily build an octree implementation based on that.
