### ISSUE TITLE
GWT cannot find module `org.joml`

### ISSUE THREAD

**Issue by sriharshachilakapati** [JOML-CI/JOML#109]
If the module is renamed to `org.joml` then the GWT compiler expects it to be in `org/joml.gwt.xml` file. This is causing a build issue with the projects using it. This was the case when I added the inherit statement as follows:

~~~xml
<inherits name="org.joml"/>
~~~

Then it tries to find `org/joml.gwt.xml` file, and complains as follows:

~~~
Loading inherited module 'org.joml'
      [ERROR] Unable to find 'org/joml.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
~~~

Trying to forcing it to use `joml.gwt.xml` file in the root, I removed the `org` prefix in the inherits line, and then a strange error popped up:

https://gist.github.com/sriharshachilakapati/3e210f4c822d6782915002a41266f60d

This doesn't directly mention JOML, but goes away when I removed the JOML dependency entirely, so it might be with this corrupt module file location. You should move it to the `org` folder in case you need it to be `org.joml`.

**Comment by httpdigest** [comment]
Sorry for that!
I did not properly test that version.
A new 1.9.3-SNAPSHOT with a rename to "joml" is deployed on oss.sonatype.org.
Obviously, the 1.9.2 release of joml-gwt is broken. Time for a quick 1.9.3 release. :)

**Comment by httpdigest** [comment]
I would like for the module to be named "org.joml", but due to GWT's package visibility rules, that does not seem possible, because it also needs to see the java/ skeleton classes at the classpath root.

**Comment by sriharshachilakapati** [comment]
I have been tweaking the JOML sources a bit and had been able to get the module named as `org.joml.JOML` according to the standard GWT conventions. I have also fixed the errors that were caused because you were using `source` element to add jre replacements where you should have been using the `super-source` tag. It's too late tonight, I will be making a PR to the repo tomorrow.

**Comment by httpdigest** [comment]
I'll be eagerly awaiting your PR. Thanks for your support on this! Indeed, the documentation of super-source looks _exactly_ like the use-case we needed here.
