### ISSUE TITLE
`sampling.Random` isn't GWT compliant

### ISSUE THREAD

**Issue by sriharshachilakapati** [JOML-CI/JOML#110]
The `Random` class in the `sampling` package is not compliant with GWT class library. Quoting the `hasLongRotateLeft()` method:

~~~java
private static boolean hasLongRotateLeft() {
    try {
        Long.class.getDeclaredMethod("rotateLeft", new Class[] { long.class, int.class });
        return true;
    } catch (NoSuchMethodException e) {
        return false;
    }
}
~~~

On line 44, the GWT's [`Class`](https://github.com/gwtproject/gwt/blob/master/user/super/com/google/gwt/emul/java/lang/Class.java) implementation does not contain any support for reflection, and hence the compiler generates an error.

**Comment by sriharshachilakapati** [comment]
I think you can fix it by adding a small `#ifdef GWT` and return true always.

**Comment by httpdigest** [comment]
Thanks! New 1.9.3-SNAPSHOT version is up.

**Comment by httpdigest** [comment]
There was yet another issue when using the Jetty Dev server: JOML did not define _default_ property values for its three properties declared in the joml.gwt.xml. That is now the case with the latest 1.9.3-SNAPSHOT and everything works with the dev server now.

**Comment by sriharshachilakapati** [comment]
That fixed everything needed to run! Compiler still showing 19 errors in strict mode, but ignoring them, the apps run. Will investigate them further on why are the hibernate classes getting in.

Thanks for quick fixes and pushes. Will open a new issue for the remaining errors.
