### ISSUE TITLE
Change toString() of vectors

### ISSUE THREAD

**Issue by piegamesde** [JOML-CI/JOML#113]
I don't like the `toString()` of vectors. The formatting is not pretty for debugging. When I just want to write some vectors to the stdout, I don't like to first have to figure out scientific notation.

I know there is a `toString()` which accepts a NumberFormat, but do you really think I am going to put a NumberFormatter for lines like this: `System.out.println(Arrays.toString(uv));`?

The solution I propose is pretty simple: add a `public static NumberFormat DEFAULT_FORMATTER = null;` to each of the Vector classes and then add the lines

    if (DEFAULT_FORMATTER != null)
        return toString(DEFAULT_FORMATTER);

to the beginning of `toString()`. Changing these three lines would save me a lot of frustration.

**Comment by httpdigest** [comment]
The current format was chosen _exactly_ to make debugging easy when formatting multiple vectors (or the same vector over time) via simple println(). Because the vector components are properly horizontally aligned due to scientific notation, it eases debugging significantly. Would you rather try to identify the individual vector component values in outputs like these?:
```
0.000412 1234.56 1.1
12.04 1 0.0004
5922.1 22.45 0.123
```
given that people would like to see the change in vector component values of the same vector over time.

**Comment by piegamesde** [comment]
Sometimes, yes. It really depends on the data. And that's why I propose to let the programmer decide how they should be formatted by default.

**Comment by httpdigest** [comment]
I thought about it for a bit and opted for the following solution:
You can use a JVM system property `-Djoml.format=false` to disable the default NumberFormat being used by all `toString()` methods.  In this case, the numbers are formatted just like a normal `Float/Double.toString()` would.
Somehow I dislike the idea of introducing static configuration fields that have more complex types than String, Integer or Boolean, especially when a client can potentially modify those field via assignments during runtime.
Would that fit your usecase?

**Comment by piegamesde** [comment]
Having a boolean setting is just fine too. Will I be able to set this flag at runtime with `System.setProperty("joml.format", "false")`?

**Comment by httpdigest** [comment]
> Will I be able to set this flag at runtime with System.setProperty("joml.format", "false")?

Yes, when done before using any JOML class, such as in a static initializer in your class containing the main() method.

**Comment by httpdigest** [comment]
Commit https://github.com/JOML-CI/JOML/commit/baf23721f5c63dad22d7d2bc48b3ddc35637d5f7 adds the `joml.format` system property to disable the NumberFormat formatter, and also `joml.format.decimals` to control the number of decimal digits when using the default NumberFormat.
That version is also deployed as new 1.9.3-SNAPSHOT on oss.sonatype.org.

**Comment by piegamesde** [comment]
Thank you.
