### ISSUE TITLE
Problem in Matrix3d

### ISSUE THREAD

**Issue by auberondreaming** [JOML-CI/JOML#115]
In Matrix3d.java, in the method set(column, row, value): this method is supposed to return the Matrix3d, it returns nothing.  It also defaults to throwing an illegal argument exception always as the throw is outside all switch statements.

**Comment by httpdigest** [comment]
Thanks for reporting! Indeed, that method was pretty buggy. :)
Resolved with https://github.com/JOML-CI/JOML/commit/a1391b6b552a244a2abcd857cfc6a872301b8728, new 1.9.3-SNAPSHOT is up.
