### ISSUE TITLE
Wrong implementation of `testRayTriangle(Vector3fc ...`

### ISSUE THREAD

**Issue by madidier** [JOML-CI/JOML#118]
Here: https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Intersectionf.java#L1931
And there: https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Intersectiond.java#L1931

The implementations of `testRayTriangle` mistakenly delegate the intersection test to `testRayTriangleFront`. It should be `testRayTriangle`.

**Comment by httpdigest** [comment]
Thanks for reporting!

**Comment by httpdigest** [comment]
Fixed with: https://github.com/JOML-CI/JOML/commit/4cb92d39825ef241a1dcd8348e805f97ed7a3d76
