### ISSUE TITLE
findClosestPointOnTriangle returning incorrect results.

### ISSUE THREAD

**Issue by Rushpixel** [JOML-CI/JOML#119]
Hi, great library! I've found an issue where closest point on triangle will sometimes return points that aren't on the triangle. I'm on a deadline so I can't do too much testing right now, I've switched to a slower algorithm I wrote a while back and it works fine. So I don't think the errors on my end. Anyway, super useful library that has saved me tonnes of time over the last few years.

**Comment by theagentd** [comment]
I've used findClosestPointOnTriangle() extensively for triangle/circle collision detection (find the closest point on the triangle, check if distance to that point is less than circle radius) for our player physics, and we've never had any issues with this. If you could provide a test case for when the error occurs, that'd be great.

**Comment by httpdigest** [comment]
@Rushpixel thank you for your feedback and for this bug report. This method was indeed broken in some subtle ways. I ended up rewriting it based on "Real-Time Collision Detection" chapter 5.1.5 and have put it under extensive testing. The issue should be resolved with commit https://github.com/JOML-CI/JOML/commit/c7a3c1604a20c3c156da55afc1dff8212fd0b70c.

**Comment by httpdigest** [comment]
@Rushpixel a new Maven snapshot release has been pushed to oss.sonatype.org. I don't know how your build process looks like. Can you use snapshot releases of Maven artifacts from thirdparty repositories, do you build from source or do you need a non-snapshot release on Maven Central for this?

**Comment by Rushpixel** [comment]
Hi, thanks for the quick response! I'm using maven central so I just copy/pasted your changes into one of my classes, and it's working perfectly.
