### ISSUE TITLE
Set clipping planes

### ISSUE THREAD

**Issue by squishybanana04** [JOML-CI/JOML#120]
I'm writing a camera class that represents the camera as two matrices, a view matrix and a projection matrix. I know it's possible to change the near and far clipping planes, but I don't know/understand the math behind it. Is there a function built in for this? Or is there some specific math that I need to do.

**Comment by httpdigest** [comment]
Have a look at these documents:
- http://www.songho.ca/opengl/gl_projectionmatrix.html
- https://www.scratchapixel.com/lessons/3d-basic-rendering/perspective-and-orthographic-projection-matrix/opengl-perspective-projection-matrix
- http://www.terathon.com/gdc07_lengyel.pdf

As for JOML, you probably want [Matrix4f.perspective(..., near, far)](http://joml-ci.github.io/JOML/apidocs/org/joml/Matrix4f.html#perspective-float-float-float-float-) or [Matrix4f.ortho(..., near, far)](http://joml-ci.github.io/JOML/apidocs/org/joml/Matrix4f.html#ortho-float-float-float-float-float-float-).

**Comment by squishybanana04** [comment]
Is there any way to change the clipping planes without resetting the matrix? I understand that `ortho` multiplies the matrix instead of setting it, so would a call like
```java
Matrix4f.ortho(0, 1, 1, 0, newNear, newFar);
```
work?

**Comment by httpdigest** [comment]
Look at http://www.songho.ca/opengl/gl_projectionmatrix.html again. It shows exactly how each matrix element is computed.
