### ISSUE TITLE
Bounding boxes / rectangles

### ISSUE THREAD

**Issue by piegamesde** [JOML-CI/JOML#121]
I don't want to touch the discussion about this _again_ (see #73 and #74), but one thing that I need in literally _all_ of my projects related to computer graphics is the use of AABB and such. I don't even need them to have methods (although having simple point-box, box-box intersect and union would be nice), I just need a convenient and standardized way to represent such shapes. Why?

 - Say I 3 dependencies on GitHub, and they all use JOML. Two of them define their own AABB classes because they lack in this library. In my project, I defined my own too long before I included that libraries. Now I have got 3 implementations of more or less the same class and it is a nightmare.
 - Classes like FrustumIntersection provide methods like `public int intersectAab(float minX, float minY, float minZ, float maxX, float maxY, float maxZ, int mask, int startPlane)`. This include more compact versions like `public boolean testAab(Vector3fc min, Vector3fc max)`. Personally, I think it is bad style to pass multiple arguments to a function that belong together as one object. This is also problematic for returning, because the return statement doesn't allow for such practice.

**Comment by httpdigest** [comment]
Basic geometry classes have been added with https://github.com/JOML-CI/JOML/commit/4ddf9eeee3de613848b9e65de22c5e4b4cd08ced and a new build of 1.9.4-SNAPSHOT is on oss.sonatype.org.
Additional methods can be added to the classes as needed.

**Comment by piegamesde** [comment]
The implementation of the AABB uses min and max coordinates. Do min values do actually need to be less or equal to their max values? And if so, does the component check or provide some checking functionality?

**Comment by httpdigest** [comment]
> Do min values do actually need to be less or equal to their max values?

Yes. _min_ coordinates are meant to be the _minimum_ coordinates of the box and _max_ coordinates are the _maximum_ coordinates of the box. Btw. the AABB methods in Intersectionf/Intersectiond taking an AABB via primitive parameters make the same assertion, of course.

> And if so, does the component check or provide some checking functionality?

No. For the sake of efficiency it is assumed that a user knows what he/she is doing. With the current _public fields_ design of most JOML classes, it is also impossible to enforce this constraint.

**Comment by piegamesde** [comment]
So I'd suggest a correctBounds() method (or however you want to call it) that makes sure min and max coordinates are set right and swaps them if not. The user might call this one if he knows that his input might be messed up without having him to implement it himself because it is some rather simple and straightforward code.

**Comment by httpdigest** [comment]
I fail to see the usecase with this. In what situation might the user think that the corners are messed up? And how can the method assume that the min and max corners then actually represent opposing _corners_ of AABB and not just some points inside the AABB which the user is wanting to build?
I've not seen such utility method in any other AABB sources so far.
Let's restrict new methods to actual usecases.

**Comment by piegamesde** [comment]
> In what situation might the user think that the corners are messed up?

User input. Random coordinates. Generating AABB from point+size where negative size is allowed.

> And how can the method assume that the min and max corners then actually represent opposing corners of AABB and not just some points inside the AABB which the user is wanting to build?

I don't understand you point here. The coordinates of the AABB _always_ represent two opposite corners of the box, how could that mess up? I was talking about when the _wrong_ two opposite corners are used so that they don't represent the min and max corner of the AABB. 

The method could simply look something like this:

    if (minX > maxX)
      // swap minX and maxX
    if (minY > maxY)
      // swap minX and maxY
    if (minZ > maxZ)
      // swap minZ and maxZ

(A version using Math.max() and Math.min() instead of if statements if possible too)

**Comment by httpdigest** [comment]
Your request has been added with: https://github.com/JOML-CI/JOML/commit/984a634dcb09e452b6aa0c8f25fb76412399962e

Please note, however, that I am more and more inclined to again remove all the geometry-related classes and methods in the next major release of JOML. It just extends beyond the scope of JOML. JOML 2.0 will very likely get back to the roots/basics of what it was meant to be with only matrices, vectors and quaternions.
With that I hope that people would possibly contribute additional projects, something like a "joml-geometry" or something, reviving and improving on the geometry classes now JOML.

**Comment by piegamesde** [comment]
Thank you.

**Comment by piegamesde** [comment]
Just tried out the new classes. There isn't an int version, is this on purpose? If yes, why? If not, can we please add them, at least for the bounding boxes?
