### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by defoye** [JOML-CI/JOML#123]
Hi.  I wonder if symbolic and numerical differentiation would be relevant/useful for this project?  I have a system that computes derivatives both symbolically and numerically.  I would be glad to add it to this project.

**Comment by httpdigest** [comment]
Thanks for the proposal. I appreciate it! However, adding the capabilities of a Computer Algebra System is beyond the scope of JOML. In the field of Compute Graphics and related fields such as Linear Algebra and Physics all formula are pretty much already known and just have to be implemented in an efficient manner.
There is very seldomly (I had not encountered a single time) the need for actually deriving a formula.

**Comment by defoye** [comment]
thanks for the info!
