### ISSUE TITLE
vector set operations

### ISSUE THREAD

**Issue by jjYBdx4IL** [JOML-CI/JOML#124]
Are there any vector set operations in JOML? i.e. calculating the average of a set of vectors, weighted average etc.?

**Comment by httpdigest** [comment]
No, there aren't. I fear that any such solution would be too opinionated about how to provide the set. Array,  Set, Collection or just anything implementing Iterable, or just Iterator, or probably people prefer a NIO Buffer. It depends too much on your concrete use case.

**Comment by jjYBdx4IL** [comment]
In conjunction with OpenGL the obvious use case is probably to calculate properties of an object for which you want to calculate a matrix to fit it into your 'world', ie. get its outer dimensions, geometrical center, center of gravity etc. But, yeah, you can probably make that part of your development/build process and avoid runtime calculations.
