### ISSUE TITLE
Vector conversion

### ISSUE THREAD

**Issue by piegamesde** [JOML-CI/JOML#125]
A more easy way to convert between different Vector** types would be nice. There is already such functionality for Vector*f and Vector*d in the constructor, the set() methods and such. But Vector*i doesn't have this, so that I have to do

    new Vector3d(vec3i.x, vec3i.y, vec3i.z);

which isn't really nice and user-friendly. I'm proposing to add at least int->float->double compatibility, and perhaps also backwards double->float->int if we can agree on type casting as standard for rounding.

**Comment by httpdigest** [comment]
Sure thing. All safe int -> float -> double copy constructors and setters should be in place with: https://github.com/JOML-CI/JOML/commit/53a4b7858cebe5e6a98dc43f1b04a656cdfaf2e5

**Comment by piegamesde** [comment]
Thanks. How can I get the 1.9.4 (or generally the latest version of this library) in Maven?

**Comment by httpdigest** [comment]
The latest snapshot is always deployed on oss.sonatype.org.
See: https://github.com/JOML-CI/JOML/wiki
