### ISSUE TITLE
Problem with Quaternion.lookAlong

### ISSUE THREAD

**Issue by Xayton** [JOML-CI/JOML#127]
I have been using `Quaternionf.lookAlong` to apply a billboard effect, but the result is not what I expected. So I tried with `Matrix4f.billboardSpherical`, converted it back to a quaternion and it worked correctly.

I expected the two methods to produce the same result, here is an example code:
```
Quaternionf q1 = new Quaternionf();
Quaternionf q2 = new Quaternionf();

Vector3f position = new Vector3f(0, 0, 0);
Vector3f target = new Vector3f(1, 1, 1);
Vector3f up = new Vector3f(0, 1, 0);

// 1) Create the quaternion using the lookAlong method.
Vector3f dir = new Vector3f();
target.sub(position, dir);
q1.lookAlong(dir, up);

// 2) Create a matrix with billboardSpherical, then convert it to a quaternion.
Matrix4f m = new Matrix4f();
m.billboardSpherical(position, target, up);
q2.setFromNormalized(m);

System.out.println("Q1: "+q1);
System.out.println("Q2: "+q2);
```

And here is the result I got:
```
Q1: (2,798E-1 -3,647E-1 -1,159E-1 8,805E-1)
Q2: (-2,798E-1 3,647E-1 1,159E-1 8,805E-1)
```

It's like the first quaternion has x, y and z inverted. I checked the source code and in fact there are some subtractions involved and in the `lookAlong` code they are inverted compared to `billboardSpherical`.

Am I doing something wrong or is there a bug in the `lookAlong` method?
Thank you

**Comment by httpdigest** [comment]
`Matrix4.lookAlong/setLookAlong` work the same way as `lookAt/setLookAt`. That is, they create a camera transformation and _not_ an object transformation, as does `Matrix4.billboard*`. This is why your two quaternions are exactly their inverse/conjugate.

However, there _is_ indeed a bug in `Matrix4/3.setLookAlong/lookAlong`, which will be fixed in a minute.

**Comment by Xayton** [comment]
OK, I understand.

I use quaternions to represent 3D object orientations, not matrices; I think the most efficient way to do billboarding will be to use `Quaternion.lookAlong`, instead of `Matrix4.billboardSpherical` and then converting.

```
Quaternionf q1 = new Quaternionf();
q1.lookAlong(dir, up);
q1.conjugate();
```

Thank you for your help and great work!

**Comment by httpdigest** [comment]
Thanks!

Please use `setLookAlong()` on a fresh/unit quaternion, and not `lookAlong`.  The latter performs a (unnecessary) multiplication.

However, *most efficient* depends on what you are going to do with the quaternion afterwards. If it is to transform it into a matrix for submission to a shader program, then likely working with matrices directly is more efficient in terms of runtime.
