### ISSUE TITLE
Complex numbers support

### ISSUE THREAD

**Issue by germangb** [JOML-CI/JOML#128]
Since JOML already has quaternions to help with 3d rotations, would it make sense to also have **ℂ**omplex numbers to aid with vec2 rotations?

**Comment by httpdigest** [comment]
I haven't heard of any real use-cases for complex numbers for 2D rotations. After all, quaternions can just be used for them with the axis (0, 0, 1). One could certainly use the class Quaternionf as a basis to implement a more efficient "Quat2f" class by eliminating x and y components of the quaternion in all operations (i.e. assuming they are 0 in this special case).

**Comment by germangb** [comment]
Even though, I think having them would make JOML more "algebraic-complete" (?) for more applications other that computer graphics.

**Comment by httpdigest** [comment]
Closing for now. If someone/you wants to provide a PR, I will gladly review/accept.
