### ISSUE TITLE
Inconsistent variable access levels in Matrix classes

### ISSUE THREAD

**Issue by IkeOTL** [JOML-CI/JOML#130]
Matrix4f has its mXX variables as protected. While Matrix3f has its mXX variables as public.

Is this on purpose?

Matrix4f currently:
`float m00, m01, m02, m03;`
`float m10, m11, m12, m13;`
`float m20, m21, m22, m23;`
`float m30, m31, m32, m33;`

Matrix3f currently:
`public float m00, m01, m02;`
`public float m10, m11, m12;`
`public float m20, m21, m22;`

**Comment by httpdigest** [comment]
Yes, this is on purpose. See:
- the release notes of version [1.8.1](https://github.com/JOML-CI/JOML/releases/tag/1.8.1)
- [this commit](https://github.com/JOML-CI/JOML/commit/4953e3bd11a38c0f5c82da719e9785e5fb153078) in this release

**Comment by IkeOTL** [comment]
I'm currently working on a physics engine, and access Matrix4f members regularly. Is the optimization this gives worth the small overhead for calling functions? 

Here's an example of what one of my functions currently looks like:
```
testAxis(other, toCenter, m.m01() * o.m02() - m.m02() * o.m01(), m.m02() * o.m00() - m.m00() * o.m02(), m.m00() * o.m01() - m.m01() * o.m00(), 6, penData);
testAxis(other, toCenter, m.m01() * o.m12() - m.m02() * o.m11(), m.m02() * o.m10() - m.m00() * o.m12(), m.m00() * o.m11() - m.m01() * o.m10(), 7, penData);
testAxis(other, toCenter, m.m01() * o.m22() - m.m02() * o.m21(), m.m02() * o.m20() - m.m00() * o.m22(), m.m00() * o.m21() - m.m01() * o.m20(), 8, penData);
testAxis(other, toCenter, m.m11() * o.m02() - m.m12() * o.m01(), m.m12() * o.m00() - m.m10() * o.m02(), m.m10() * o.m01() - m.m11() * o.m00(), 9, penData);
testAxis(other, toCenter, m.m11() * o.m12() - m.m12() * o.m11(), m.m12() * o.m10() - m.m10() * o.m12(), m.m10() * o.m11() - m.m11() * o.m10(), 10, penData);
testAxis(other, toCenter, m.m11() * o.m22() - m.m12() * o.m21(), m.m12() * o.m20() - m.m10() * o.m22(), m.m10() * o.m21() - m.m11() * o.m20(), 11, penData);
testAxis(other, toCenter, m.m21() * o.m02() - m.m22() * o.m01(), m.m22() * o.m00() - m.m20() * o.m02(), m.m20() * o.m01() - m.m21() * o.m00(), 12, penData);
testAxis(other, toCenter, m.m21() * o.m12() - m.m22() * o.m11(), m.m22() * o.m10() - m.m20() * o.m12(), m.m20() * o.m11() - m.m21() * o.m10(), 13, penData);
testAxis(other, toCenter, m.m21() * o.m22() - m.m22() * o.m21(), m.m22() * o.m20() - m.m20() * o.m22(), m.m20() * o.m21() - m.m21() * o.m20(), 14, penData);
```

As you can see the tiny overhead for calling functions might start to have an impact?

**Comment by httpdigest** [comment]
Unless you are on Android (in which case you should be using joml-android), there will be absolutely no overhead. Please measure (for example with JMH) instead of assuming/guessing.
