### ISSUE TITLE
Vector3f.set(int i, int f) and Vector3f.x(float f)

### ISSUE THREAD

**Issue by IkeOTL** [JOML-CI/JOML#133]
There is a Vector3f.get(i), that returns the value of the respective vector component, but there isn't on to set the vector components.

For example:
```
    vec3.set(0, 1337);
    vec3.x(1337)
```

Would be equal to vec3.x = 1337;

```
public void set(int component, float f) throws IllegalArgumentException {
    switch (component) {
        case 0:
            this.x = f;
            break;
        case 1:
            this.y = f;
            break;
        case 2:
            this.z = f;
            break;
        default:
            throw new IllegalArgumentException();
    }
}
```

**Comment by httpdigest** [comment]
Vector.set(component, value) methods have been added with: https://github.com/JOML-CI/JOML/commit/d813e533cd1b08c0134b4a614c575191fbeb8ef6

I do see the necessity to use the `set` method with a computed component/index, however I fail to see why we need a "static" setter method for x, y or z. When you know at compile-time which exact component you need to modify, then just assign to the field.
