### ISSUE TITLE
mul() in Vector3i

### ISSUE THREAD

**Issue by piegamesde** [JOML-CI/JOML#135]
Look what I found in Vector3i:

    /**
     * Add the supplied vector by this one.
     *
     * @param v
     *          the vector to multiply
     * @return this
     */
    public Vector3i mul(Vector3ic v) {
        x += v.x();
        y += v.y();
        z += v.z();
        return this;
    }

Either the doc or the implementation is wrong, or I am dumb. To me this looks pretty much like a copy-paste-error.

**Comment by httpdigest** [comment]
You are absolutely right! Thank you for reporting this bug.

**Comment by piegamesde** [comment]
I just found it by hazard while doing my immutable vector thing: https://github.com/piegamesde/JOML/commit/f0c58ee8a08399e8f732578f1bc9a996c1613f37
