### ISSUE TITLE
Intersecting line segment with polygon?

### ISSUE THREAD

**Issue by seanoperc** [JOML-CI/JOML#139]
I'm looking to not only detect the intersection of a line segment with a polygon, but also to find the points at which the line segment intersects the polygon, to calculate the length of the intersection for path planning.
I thought JOML had one or more methods to calculate the intersection of a line segment with a polygon, but if it does I can't find it.  Before I go reinventing the wheel, am I just being blind or am I correct that the such a method does not exist?  The polygon/ray intersection method almost does what I need;
https://joml-ci.github.io/JOML/apidocs/org/joml/Intersectionf.html#intersectPolygonRay-float:A-float-float-float-float-org.joml.Vector2f-
I can see how to use that to get _an_ intersection point, but I don't see a reasonable way to use that to get multiple intersection points, i.e. where the ray enters/leaves the poly.  Any suggestions?  

Sean Owens

**Comment by httpdigest** [comment]
One way is to reverse the ray direction (just negate the direction's components) and offset the ray's starting point, such as by using the first detected hit point offset by the radius of the polygon's circumscribed circle (or any offset large enough to cover the whole polygon).

**Comment by seanoperc** [comment]
Hmm, good point.  Does intersectPolygonRay() require a convex polygon?  If
so then there should be at most two intersections.  I can call
intersectPolygonRay() with one end of the segment as origin; if it returns
an intersection I can run the intersection point through the line's
parametric representation to make sure it's on the segment.   If it is then
I can call it again using the other end of the segment and shooting the ray
in the opposite direction. But if it's a non convex polygon, hmmm.

**Comment by httpdigest** [comment]
> Does intersectPolygonRay() require a convex polygon?

No. That method is essentially computing intersections between the ray and a set of edges and returns the intersection nearest to the ray's origin. So it will work with any polygons.

**Comment by seanrowens** [comment]
Aha, I see!  All right then I'll implement a convex polygon intersection
method on top of that.  Thanks.
