### ISSUE TITLE
Cannot run on Android Studio 3.0

### ISSUE THREAD

**Issue by CatsNipYummy** [JOML-CI/JOML#142]
I added JOML to an Android Studio 3.0 project and synced it successfully. But when I run the project, I get the following error:

`Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/3.jar --output /Users/user/TestApp/app/build/intermediates/transforms/desugar/debug/8.jar --input /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/27.jar --output /Users/user/TestApp/app/build/intermediates/transforms/desugar/debug/32.jar --input /Users/anil.u/Repo/SDKApp/sdk/android/base/build/intermediates/intermediate-jars/debug/classes.jar --output /Users/user/TestApp/app/build/intermediates/transforms/desugar/debug/3.jar --input /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/8.jar --output /Users/user/TestApp/app/build/intermediates/transforms/desugar/debug/13.jar --classpath_entry /Users/anil.u/Repo/SDKApp/sdk/android/engines/mfaceb/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/anil.u/Repo/SDKApp/sdk/android/mface/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/anil.u/Repo/SDKApp/sdk/android/utility/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/anil.u/Repo/SDKApp/sdk/android/base/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/classes/debug --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/0.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/1.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/2.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/3.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/4.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/5.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/6.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/7.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/8.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/9.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/10.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/11.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/12.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/13.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/14.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/15.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/16.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/17.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/18.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/19.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/20.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/21.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/22.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/23.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/24.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/25.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/26.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/27.jar --classpath_entry /Users/user/TestApp/app/build/intermediates/transforms/stackFramesFixer/debug/28.jar --bootclasspath_entry /Users/anil.u/Library/Android/sdk/platforms/android-26/android.jar --bootclasspath_entry /Users/anil.u/Library/Android/sdk/platforms/android-26/optional/org.apache.http.legacy.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/resources.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/rt.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/jsse.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/jce.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/charsets.jar --min_sdk_version 23 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}`

Is this related to:
[https://github.com/gradle/gradle/issues/2384](url)
[https://issuetracker.google.com/issues/63265765](url)

I can't go back to Android Studio 2.3.3 cause of the NDK support.

**Comment by httpdigest** [comment]
> Is this related to:
https://github.com/gradle/gradle/issues/2384
https://issuetracker.google.com/issues/63265765

Probably. Did you use org.joml:joml-android:1.9.3-SNAPSHOT as Gradle dependency, as suggested by the Wiki: https://github.com/JOML-CI/JOML/wiki#gradle-setup-for-android ?

**Comment by CatsNipYummy** [comment]
> Did you use org.joml:joml-android:1.9.3-SNAPSHOT as Gradle dependency, as suggested by the Wiki: https://github.com/JOML-CI/JOML/wiki#gradle-setup-for-android ?

Yes I did. Didn't solve the issue for me.

**Comment by httpdigest** [comment]
Can you provide a little bit more information about your build setup, then? Like your Gradle build file. Does your project contain _only_ the JOML library and nothing else? If not, then I highly doubt that JOML is being the cause.
Please provide a _minimal_ example project that reproduces the issue.

**Comment by CatsNipYummy** [comment]
This issue came up when I added JOML to a project. But when I add JOML to an empty project, I'm not getting the error. So like you said, its probably not JOML that's causing this issue.

**Comment by httpdigest** [comment]
Just inspect the build.gradle file of your failing project and see whether the IDE is complaining about some plugin versions being outdated. It is likely that when you create a complete new project Android Studio already configures more recent versions of the plugins/dependencies for you which work.
