### ISSUE TITLE
Vector rotateXYZ doesn't work right.

### ISSUE THREAD

**Issue by ramzanzan** [JOML-CI/JOML#143]
Second string, angle * 0.5 - it's some mistake, with angel=PI vector is rotated only PI/2

//mistake is present in all Vector classes, not only 3f
public Vector3f rotateZ(float angle, Vector3f dest) {
        float sin = (float) Math.sin(angle * 0.5), cos = (float) Math.cosFromSin(sin, angle * 0.5);
        ...
}

**Comment by httpdigest** [comment]
Great find! Thanks for reporting. Fixed with https://github.com/JOML-CI/JOML/commit/d86bfdfcf99528b5d27d4436dbcac4bd869e01e5
