### ISSUE TITLE
Matrix4f.setLookAlong(Vector3fc, Vector3fc) does not behave as documented

### ISSUE THREAD

**Issue by slyh80** [JOML-CI/JOML#147]
The documentation of method `Matrix4f.setLookAlong(Vector3fc, Vector3fc)` states the following:

> This is equivalent to calling setLookAt() with eye = (0, 0, 0) and center = dir.

If one calls setLookAt() exactly like this, it won't lead to an equivalent result, though.

Test case:

```
    public void lookAlongLookAtTest() {
         Vector3f eye = new Vector3f(0, 0, 0);
         Vector3f direction = new Vector3f(-1.0f, -0.5f, -0.5f);
         Vector3f up = new Vector3f(0, 1, 0);
         
         Matrix4f m1 = new Matrix4f();
         Matrix4f m2 = new Matrix4f();
         
         m1.setLookAt(eye, direction, up);
         m2.setLookAlong(direction, up);
         
         System.out.println(m1.equals(m2));
     }
```
This will print "false", but should print "true". (The resulting matrix is similar, but different in several positions.)

**Comment by httpdigest** [comment]
Thank you for reporting this bug!
Indeed, those methods (and their Quaternion counterparts) were slightly wrong.
This has been fixed with: https://github.com/JOML-CI/JOML/commit/6d15088cffd72b92f2f7c205b1f57b6206042ee5

**Comment by httpdigest** [comment]
A new org.joml:joml:1.9.8-SNAPSHOT build is up on oss.sonatype.org, in case you want to have this fix and are using Maven/Gradle.

**Comment by slyh80** [comment]
Verified the SNAPSHOT against my test case and real-world usage. Looks good to me now.
Thanks for the awesome response time on this issue, and the overall quality of JOML. Really great work!
