### ISSUE TITLE
Vector2d and Vector2f `mulDirection` overloads call `mulPosition`

### ISSUE THREAD

**Issue by donovanMaas** [JOML-CI/JOML#148]
In the [Vector2d](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Vector2d.java#L623) and [Vector2f](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Vector2f.java#L786) classes the `mulDirection(Matrix3x2tc)` methods call `mulPosition(Matrix3x2tc, Vector2t)` instead of the `mulDirection(Matrix3x2tc, Vector2t)`. This is unlike any of the other Vector classes. Is this correct behavior?

**Comment by httpdigest** [comment]
Thank you for reporting! Fixed with https://github.com/JOML-CI/JOML/commit/d591f7aafe26f5700f8c7845402df3414693fc63
