### ISSUE TITLE
Vector4d `mul(Vector4tc)` and `mul(Vector4dc)` does not properly manipulate `w`.

### ISSUE THREAD

**Issue by donovanMaas** [JOML-CI/JOML#151]
The [`mul(Vector4dc)`](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Vector4d.java#L881-L887), [`div(Vector4dc)`](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Vector4d.java#L907-L913), and [`mul(Vector4fc)`](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Vector4d.java#L933-L939) methods in Vector4d do not properly manipulate the `w` component. They instead multiply/divide the `z` component by the multiplier's/divisor's `w` component.

**Comment by httpdigest** [comment]
Thanks alot for finding and reporting all those bugs! :)
