### ISSUE TITLE
Matrix4f.unprojectRay() and other fov than 90

### ISSUE THREAD

**Issue by AndrewAlfazy** [JOML-CI/JOML#153]
Hi!,
I'm not sure if it is math problem or my problem. When I try to use Matrix4f.unprojectRay() and I'm sure from the values I used, It gives me result isn't true ,when I change the FoV by any value other than 90 it gives me the same result of FoV 90.
sorry for my bad English.

Andrew

**Comment by httpdigest** [comment]
Can you please show the exact source code line where you call that method with the exact arguments?
Are you sure you used radians as the fov argument and _not_ degrees?

**Comment by AndrewAlfazy** [comment]
fb is a FloatBuffer
`	private static final float NEAR = 0.1f, FAR = 200, FOV = 120,
		ASPECT =1280 /1024;
	public static void go3D() {
		posY = Terrain.getY(posX, posZ);
		rotR = (float) Math.toRadians(rotD);
		camX = (float) ((float) posX + (Math.sin(rotR) * 10d));
		camZ = (float) ((float) posZ + (Math.cos(rotR) * 10d));
		camY = posY + 25;
		viewMatrix.identity();
		viewMatrix.setPerspective((float) Math.toRadians(FOV), ASPECT, NEAR, FAR);
		glMatrixMode(GL_PROJECTION);
		glLoadMatrixf(viewMatrix.get(fb));
		viewMatrix.setLookAt(camX, camY, camZ, posX, posY, posZ, 0, 1, 0);
		glMatrixMode(GL_MODELVIEW);
		glLoadMatrixf(viewMatrix.get(fb));
	}
	public static Matrix4f getViewMatrix() {
		return new Matrix4f(viewMatrix);
	}`
`	private static Rayf ray = new Rayf();
	private static int info[] = {0, 0, 1280, 1024};
	public static Rayf GetRay() {
		Vector3f rayO = new Vector3f(), rayD = new Vector3f();
		View.getViewMatrix().unprojectRay(Mouse.getMosuePos(), info, rayO, rayD);
		ray = new Rayf(rayO, rayD);
		return ray;
	}`

**Comment by httpdigest** [comment]
Use blocks enclosed in three backticks \```Java ...code... \```
As for your problem: You are not actually unprojecting the combined view-projection matrix. You are only unprojecting the `View` matrix. This essentially gives you an orthogonal projection.

**Comment by AndrewAlfazy** [comment]
thank you very much I understood. sorry for annoying You.
