### ISSUE TITLE
Matrix4f tests

### ISSUE THREAD

**Issue by AndrewAlfazy** [JOML-CI/JOML#154]
testAab() make it work with "AABBf" not just with values (minX,maxY, etc) 
dont forget testPoint (Vector3f) and Sphere (Spheref).
and 'd' (Matrix4d)
Make your Library work with it self.
and I have a question why there is AABB class and there isn't OBB Class?

**Comment by httpdigest** [comment]
> why there is AABB class and there isn't OBB Class?

Because it has not been implemented yet.
