### ISSUE TITLE
Why there are no matrices with size 2 to 2?

### ISSUE THREAD

**Issue by VAVUS7** [JOML-CI/JOML#157]
Why there are no matrices with size 2 to 2?

**Comment by httpdigest** [comment]
Because they have pretty much no application in 2D and 3D graphics. With 2D you at least want 3x2 to account for translation.

**Comment by VAVUS7** [comment]
But OpenG has the function glUniformMatrix2fv

**Comment by httpdigest** [comment]
OpenGL has many functions. Do you use it?

**Comment by VAVUS7** [comment]
No. It was just interesting
