### ISSUE TITLE
JDK 10 Illegal access error.

### ISSUE THREAD

**Issue by yiandev** [JOML-CI/JOML#158]
Hi, just installed jdk10 today with intellij 2017.3.5 and got this illegal access error from joml jar.
I got JOML from LWJGL page, should be the same tough.

![error](https://user-images.githubusercontent.com/31630982/37667838-a407de3a-2c6b-11e8-8e50-c4f56c1d316b.jpg)

The program seems to be working fine but i get the error everytime i launch.
Hopefully its not a big breaking change.

**Comment by httpdigest** [comment]
Thanks for letting me know. This is fixed with https://github.com/JOML-CI/JOML/commit/448b6405a9514b7b43711b53ff6732370929b11b. Next Maven 1.9.9-SNAPSHOT version will be available in about two hours.

**Comment by httpdigest** [comment]
You can now download the 1.9.9-SNAPSHOT version via Maven `org.joml:joml:1.9.9-SNAPSHOT` from the  https://oss.sonatype.org/content/repositories/snapshots Maven repository, or download the jar from the [GitHub Release page](https://github.com/JOML-CI/JOML/releases/tag/1.9.9-SNAPSHOT).
