### ISSUE TITLE
Can't Compile on Android

### ISSUE THREAD

**Issue by AlienJim** [JOML-CI/JOML#161]
I am getting an error when trying to include JOML as a dependency. The Error is 

`Illegal class file: Class module-info is missing a super type.`

In application level gradle:

```
dependencies { 
    implementation fileTree(include: '*.jar', dir: 'libs')
    implementation 'org.joml:joml:1.9.9'
    ...
} 
```

I am using android studio/gradle version 3.1 and build tools version 27.0.3.

**Comment by httpdigest** [comment]
Please see the link "Android" on the README.md, which links to: https://github.com/JOML-CI/JOML/wiki#gradle-setup-for-android

**Comment by AlienJim** [comment]
org.joml:joml-jdk8:1.9.9 is working great on the latest version of android.

Thanks
