### ISSUE TITLE
Matrix4f.getEulerAnglesZYX()/rotateZYX() broken?  (Or I'm just an idiot.)

### ISSUE THREAD

**Issue by seanrowens** [JOML-CI/JOML#162]
Based on the javadocs for Matrix4f.getEulerAnglesZYX(), the below SHOULD work, and yet does not.  It's entirely possible I'm doing something boneheadedly wrong, but I'd appreciate it if someone more knowledgeable than myself can check this out.

bash-3.2$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
bash-3.2$ cat GetEulerZYXTest.java 
import org.joml.Matrix4f;
import org.joml.Vector3f;

public class GetEulerZYXTest {
	public static void testGetEulerAngesZYX() {

		Vector3f eye = new Vector3f(0, 0, 0);
		Vector3f center = new Vector3f(0, 0, 1);
		Vector3f up = new Vector3f(0, 1, 0);
		Matrix4f m = new Matrix4f(); // <- matrix only representing rotation
		m.setLookAt(eye, center, up);
		Matrix4f n = new Matrix4f();
		System.err.println(" angles = " + m.getEulerAnglesZYX(new Vector3f()));
		n.rotateZYX(m.getEulerAnglesZYX(new Vector3f()));
		if (m.equals(n)) {
			System.err.println("Matrices are equal");
		} else {
			System.err.println("Matrices are NOT equal");
			System.err.println("m = \n" + m);
			System.err.println("n = \n" + n);
		}
	}

	public static void main(String[] args) {
		testGetEulerAngesZYX();
	}
}
bash-3.2$ javac -cp .:joml-1.9.8.jar  GetEulerZYXTest.java 
bash-3.2$ java -cp .:joml-1.9.8.jar  GetEulerZYXTest
 angles = ( 3.142E+0 -0.000E+0  3.142E+0)
Matrices are NOT equal
m = 
-1.000E+0  0.000E+0  0.000E+0 -0.000E+0
 0.000E+0  1.000E+0  0.000E+0 -0.000E+0
 0.000E+0  0.000E+0 -1.000E+0 -0.000E+0
 0.000E+0  0.000E+0  0.000E+0  1.000E+0

n = 
-1.000E+0 -8.742E-8  7.643E-15  0.000E+0
-8.742E-8  1.000E+0 -8.742E-8  0.000E+0
 0.000E+0 -8.742E-8 -1.000E+0  0.000E+0
 0.000E+0  0.000E+0  0.000E+0  1.000E+0

bash-3.2$ uname -a
Darwin MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
bash-3.2$

**Comment by httpdigest** [comment]
Both matrices are _effectively_ equal, considering rounding errors in the eights decimal place, which is totally fine for a float variable. The problem is that Matrix4f.equals() compares the float values effectively using ==, which only holds when they are _exactly_ identical. Float comparison should always use an epsilon but Object.equals() does not provide such a epsilon parameter and I am uncomfortable providing a "default" delta, since the rounding error depends on the magnitude of the values. So, you should compare matrices yourself with an appropriate epsilon.

**Comment by seanrowens** [comment]
Right, yeah, so it turns out I _am_ an idiot, was staring the mantissa and
ignoring the exponent.  Much thanks.

**Comment by piegamesde** [comment]
Maybe an overload method `equals(Matrixf other, float delta)` could be a useful thing?
