### ISSUE TITLE
Vector4i scalar multiplication with float instead of int

### ISSUE THREAD

**Issue by Wasabi375** [JOML-CI/JOML#166]
Is there any reason why the scalar to multiply a `Vector4i` with is a float and not an int? The scalar for `Vector3i` and `Vector2i` are both integers.

**Comment by httpdigest** [comment]
You're right. It should be int. However, float did not hurt, or did it? :)
Fixed with the next build.

**Comment by Wasabi375** [comment]
Not really, I'm just writing some Kotlin wrappers so I can use operator overloading and stumbled over it.
