### ISSUE TITLE
Addition of two Vector4d

### ISSUE THREAD

**Issue by alessandrofelder** [JOML-CI/JOML#170]
I think there are some problems adding `Vector4d`s
The methods
[`public Vector4d add(Vector4dc v, Vector4d dest)`](https://github.com/JOML-CI/JOML/blob/80e3012876f109e8ac4f82b0d83e6391a71e0666/src/org/joml/Vector4d.java#L731)
[`public Vector4d add(Vector4fc v, Vector4d dest)`](https://github.com/JOML-CI/JOML/blob/80e3012876f109e8ac4f82b0d83e6391a71e0666/src/org/joml/Vector4d.java#L739)
do not use the input parameter v, but add `this` to itself...
Also:
[`public Vector4d add(double x, double y, double z, double w, Vector4d dest)`](https://github.com/JOML-CI/JOML/blob/80e3012876f109e8ac4f82b0d83e6391a71e0666/src/org/joml/Vector4d.java#L767) subtracts two vectors instead of adding them. Probably the consequence of copy-pasting, the comments of the add method above say "subtract"

**Comment by httpdigest** [comment]
Indeed. Thanks for reporting it! Fixed with https://github.com/JOML-CI/JOML/commit/baed1c5dc646f1ca2ea814f77529ea8ec94a73b0
Next 1.9.12-SNAPSHOT is currently being built and uploaded to oss.sonatype.org by https://travis-ci.org/JOML-CI/JOML/jobs/427811334
