### ISSUE TITLE
translate(...) in Matrix3f

### ISSUE THREAD

**Issue by pcfreak9000** [JOML-CI/JOML#174]
Hi,
could you add translate(...) methods in Matrix3f? I'd like to use that class as 2D transform.

**Comment by httpdigest** [comment]
Hey,
you wouldn't be needing `Matrix3f` then. For the 2D case, there is `Matrix3x2f`, which contains a 2D-translate. If Matrix3x2f does not contain something that you need, it is worth adding it there.

**Comment by pcfreak9000** [comment]
I see, thank you!
