### ISSUE TITLE
Inconsistent read/write Vector4d to Buffer

### ISSUE THREAD

**Issue by abernardi597** [JOML-CI/JOML#178]
It seems that `Vector4d` is not being properly restored from NIO `Buffer` objects.
The following test case fails:
```java
@Test
void testVector4dInBuffer() {
    ByteBuffer buf = ByteBuffer.allocateDirect(4 * 8);
    Vector4dc v = new Vector4d(1, 1, 1, 1);
    v.get(0, buf);
    assertEquals(v, new Vector4d(0, buf));
}
```

I peeked at the bytes in the buffer to see if I could learn anything more.
Writing seems to work fine::
```
00 00 00 00 00 00 f0 3f 
00 00 00 00 00 00 f0 3f
00 00 00 00 00 00 f0 3f
00 00 00 00 00 00 f0 3f
```

But after writing the `Vector4d` that was read from the buffer:
```
00 00 00 00 00 f8 cf 43
00 00 00 00 00 f8 cf 43
00 00 00 00 00 f8 cf 43
00 00 00 00 00 f8 cf 43
```

Interestingly, this does not seem to be a problem for any other vector type.
I have not tested any other non-vector types.

**Comment by httpdigest** [comment]
Thanks for reporting this bug! It will be fixed with the next [1.9.14-SNAPSHOT build](https://travis-ci.org/JOML-CI/JOML/builds/518361062) and deployed to oss.sonatype.org.
