### ISSUE TITLE
MemUtil.INSTANCE.put broken for some double operations

### ISSUE THREAD

**Issue by Earthcomputer** [JOML-CI/JOML#181]
An issue I found when exploring `MemUtil` while adding `Matrix2f` and `Matrix2d`.
Certain methods in `MemUtil$MemUtilNIO` (that is, NOT the class which uses `sun.misc.Unsafe`), which write doubles to a `ByteBuffer`, appear to have been copy-pasted from the equivalent float methods and have not had their indices updated accordingly.
For example, in [this method](https://github.com/JOML-CI/JOML/blob/ce2652fc236b42bda3875c591f8e6645048a678f/src/org/joml/internal/MemUtil.java#L567-L584) the offsets are multiples of 4, whereas they should be multiples of 8.
This would cause problems when using methods like `Matrix3f.get(ByteBuffer)` under GWT, for example.

**Comment by httpdigest** [comment]
If you'd like to provide a PR for those fixes as well, that'd be great. Thanks!

**Comment by Earthcomputer** [comment]
Found another example [here](https://github.com/JOML-CI/JOML/blob/4cf7b6e00a55122090a997670a3feaeee390cbda/src/org/joml/internal/MemUtil.java#L4127) which affects `MemUtilUnsafe`, so changing the title.
I might PR a fix to these, after I finish with `Matrix2*` :)
