### ISSUE TITLE
Invert wrong after rotation

### ISSUE THREAD

**Issue by haubna** [JOML-CI/JOML#190]
```
Matrix4d rotation = new Matrix4d().rotation(0.5, new Vector3d(1.0, 0.6, 0.2));
Matrix4d inverseRotation = new Matrix4d().rotation(0.5, new Vector3d(1.0, 0.6, 0.2)).invert();
rotation.mul(inverseRotation);
```
will not result in the identity matrix but it should.
```
Matrix4d rotation = new Matrix4d().rotation(0.5, new Vector3d(1.0, 0.6, 0.2));
Matrix4d inverseRotation = new Matrix4d().rotation(0.5, new Vector3d(1.0, 0.6, 0.2)).determineProperties().invert();
rotation.mul(inverseRotation);
```
or
```
Matrix4d rotation = new Matrix4d().rotation(0.5, new Vector3d(1.0, 0.6, 0.2));
Matrix4d inverseRotation = new Matrix4d().rotation(0.5, new Vector3d(1.0, 0.6, 0.2)).invertAffine();
rotation.mul(inverseRotation);
```
fixes this. I guess the properties are wrong after a rotation.

**Comment by httpdigest** [comment]
Please see the JavaDoc documentation of the [Matrix4d#rotation(float, Vector3dc)](https://joml-ci.github.io/JOML/apidocs/org/joml/Matrix4d.html#rotation(double,org.joml.Vector3dc)) method:
>  The axis described by the axis vector needs to be a unit vector.

Otherwise, you'd also get scaling, which is very likely not desired.

**Comment by haubna** [comment]
Oh ok thx! :)

Kai Burjack <notifications@github.com> schrieb am Di. 3. Sep. 2019 um 10:34:
