### ISSUE TITLE
My view matrix is full of NaNs after lookat

### ISSUE THREAD

**Issue by True-han** [JOML-CI/JOML#194]
After 'lookat' transformation my view matrix doesn't work.
I'm so bad at math so I tried to log my camera's vectors and matrix.

A part of log:
```[pos] ( 3.607E+0  6.119E-1  4.617E+0)
[center] ( 4.509E+0  7.649E-1  5.022E+0)
[front] ( 9.017E-1  1.530E-1  4.043E-1)
[up] ( 0.000E+0  1.000E+0  0.000E+0)

[view] NaN NaN NaN NaN
NaN NaN NaN NaN
NaN NaN NaN NaN
NaN NaN NaN NaN

[pos] ( 5.410E+0  9.179E-1  5.426E+0)
[center] ( 6.312E+0  1.071E+0  5.830E+0)
[front] ( 9.017E-1  1.530E-1  4.043E-1)
[up] ( 0.000E+0  1.000E+0  0.000E+0)

[view] NaN NaN NaN NaN
NaN NaN NaN NaN
NaN NaN NaN NaN
NaN NaN NaN NaN

[pos] ( 7.214E+0  1.224E+0  6.234E+0)
[center] ( 8.116E+0  1.377E+0  6.639E+0)
[front] ( 9.017E-1  1.530E-1  4.043E-1)
[up] ( 0.000E+0  1.000E+0  0.000E+0)

[view] NaN NaN NaN NaN
NaN NaN NaN NaN
NaN NaN NaN NaN
NaN NaN NaN NaN

[pos] ( 9.017E+0  1.530E+0  7.043E+0)
[center] ( 9.919E+0  1.683E+0  7.447E+0)
[front] ( 9.017E-1  1.530E-1  4.043E-1)
[up] ( 0.000E+0  1.000E+0  0.000E+0)

[view] NaN NaN NaN NaN
NaN NaN NaN NaN
NaN NaN NaN NaN
NaN NaN NaN NaN
```
Transformation: `view.lookAt(cameraPosition, cameraPosition.add(cameraFront), cameraUp);`

Please help me, I'm really bad at math.

**Comment by httpdigest** [comment]
The culprit is these two arguments you are using: `cameraPosition, cameraPosition.add(cameraFront)`.
Please read the JavaDoc documentation of the Vector add method you are using and read this: cameraPosition, cameraPosition.add(cameraFront)

**Comment by True-han** [comment]
> The culprit is these two arguments you are using: `cameraPosition, cameraPosition.add(cameraFront)`.
> Please read the JavaDoc documentation of the Vector add method you are using and read this: https://github.com/JOML-CI/JOML/wiki/Common-Pitfalls#methods-without-a-dest-parameter-modify-this-and-return-this

Thank you!
