### ISSUE TITLE
Quaterniond slerp seems broken

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#197]
The `Quaterniond#slerp()` method seems broken. Here is a chart showing the value of `alpha` blending from 0 to 1 linearly (top), the resulting rotation angle (middle), and the resulting three axis values (bottom). As `alpha` surpasses about 0.25, both the angle and the axes go to zero.

![image](https://user-images.githubusercontent.com/811305/68543238-c6d11380-0371-11ea-88b3-001753ccdc71.png)

The code for `slerp()` is very different from the code given on Wikipedia's page -- maybe you should try their version instead:

https://en.wikipedia.org/wiki/Slerp#Source_code

**Comment by lukehutch** [comment]
Sorry, I realize I was calling the API wrong. I misinterpreted the API param names, thinking I could call it like this to interpolate between no rotation and `quat`, storing the result in a new `Quaterniond`:

`slerpResult = quat.slerp(new Quaterniond(), alpha)`

whereas the first quaternion parameter is the target, not the destination. I guess I should have been calling this:

`slerpResult = new Quaterniond().slerp(quat, alpha, new Quaterniond())`

**Comment by httpdigest** [comment]
Yes, all API methods in JOML have a `applies to this` and an additional `applies to dest` overload. This is to give the client full control over object allocation / GC.
See: https://github.com/JOML-CI/JOML/wiki/Common-Pitfalls#methods-without-a-dest-parameter-modify-this-and-return-this

**Comment by lukehutch** [comment]
Thanks, yes, I thought it was odd that the destination parameter was in the first position for this method (it wasn't -- I didn't see there was another method with the destination parameter as the last method, as with other method calls).

Thanks for the rapid responses, and sorry for the misunderstandings!

**Comment by httpdigest** [comment]
No worries, I'm glad we could sort this out so quickly as well. Have fun with JOML! :)

**Comment by lukehutch** [comment]
Thanks. Is there a place other than this bug tracker to ask quick questions?

**Comment by httpdigest** [comment]
Nothing explicitly dedicated to JOML. You can use StackOverflow or if you feel like it you can join the LWJGL Slack via http://slack.lwjgl.org/ and post into the "joml" channel.

**Comment by lukehutch** [comment]
Sorry to reopen, but I found a discrepancy between the JOML slerp results and the Wikipedia algorithm slerp results. Here are the JOML results -- again the top graph shows the value of `alpha`, the middle shows the angle of the quaternion, and the bottom shows the quaternion axis, over a series of consecutive quaternion interpolations:

![image](https://user-images.githubusercontent.com/811305/68544184-c3dc2000-037d-11ea-814b-7f95b5c4530d.png)

Here is the result of the Wikipedia algorithm:

![image](https://user-images.githubusercontent.com/811305/68544192-d6565980-037d-11ea-9797-80986fe6aff5.png)

Here's the ported version of the [Wikipedia algorithm code](https://en.wikipedia.org/wiki/Slerp#Source_code):

```java
private static Quaterniond slerp(Quaterniond v0, Quaterniond v1, double t) {
    // Only unit quaternions are valid rotations.
    // Normalize to avoid undefined behavior.
    v0.normalize();
    v1.normalize();

    // Compute the cosine of the angle between the two vectors.
    double dot = v0.dot(v1);

    // If the dot product is negative, slerp won't take
    // the shorter path. Note that v1 and -v1 are equivalent when
    // the negation is applied to all four components. Fix by 
    // reversing one quaternion.
    if (dot < 0.0f) {
        v1 = new Quaterniond(-v1.x, -v1.y, -v1.z, -v1.w);
        dot = -dot;
    }

    double DOT_THRESHOLD = 0.9995;
    if (dot > DOT_THRESHOLD) {
        // If the inputs are too close for comfort, linearly interpolate
        // and normalize the result.
        Quaterniond result = new Quaterniond(v0.x + t * (v1.x - v0.x), v0.y + t * (v1.y - v0.y),
                v0.z + t * (v1.z - v0.z), v0.w + t * (v1.w - v0.w)).normalize();
        return result;
    }

    // Since dot is in range [0, DOT_THRESHOLD], acos is safe
    double theta_0 = Math.acos(dot); // theta_0 = angle between input vectors
    double theta = theta_0 * t; // theta = angle between v0 and result
    double sin_theta = Math.sin(theta); // compute this value only once
    double sin_theta_0 = Math.sin(theta_0); // compute this value only once

    double s0 = Math.cos(theta) - dot * sin_theta / sin_theta_0; // == sin(theta_0 - theta) / sin(theta_0)
    double s1 = sin_theta / sin_theta_0;

    return new Quaterniond(s0 * v0.x + s1 * v1.x, s0 * v0.y + s1 * v1.y, s0 * v0.z + s1 * v1.z,
            s0 * v0.w + s1 * v1.w).normalize();
}
```

The final endpoints of each angle interpolation are the same, and the axis interpolations are the same, but the Wikipedia algorithm seems to quadratically interpolate the angle, whereas the JOML algorithm seems to linearly interpolate the angle. Is there a "correct" way to do this? The JOML chart looks more naturally correct to me, but presumably many more eyes have looked at the Wikipedia page than JOML.

**Comment by httpdigest** [comment]
As I said previously, I think the Quaternion (-) operator in the C++ source code computes the conjugate whereas you negate all components (effectively not changing the quaternion at all):
Change:
```
        v1 = new Quaterniond(-v1.x, -v1.y, -v1.z, -v1.w);
```
to:
```
        v1 = new Quaterniond(-v1.x, -v1.y, -v1.z, v1.w);
```

**Comment by lukehutch** [comment]
Good catch, sorry, I forgot to change that in the code after reading your comment.

However even after I make that change, the results are identical (for the quaternions I'm testing with, at least -- so I guess the `if (dot < 0.0f)` code path is not followed in any of the slerp calls shown in the graph).

**Comment by httpdigest** [comment]
I think the JOML implementation was based on: https://www.euclideanspace.com/maths/algebra/realNormedAlgebra/quaternions/slerp/index.htm#code (search for "code").

**Comment by lukehutch** [comment]
Great link, thanks. I raised the issue on the Wikipedia talk page, I think JOML is correct.

**Comment by httpdigest** [comment]
Probably better reference the code from this paper: http://fabiensanglard.net/doom3_documentation/37725-293747_293747.pdf rather than JOML, or add that the JOML implementation is this.
