### ISSUE TITLE
Quaterniond `invert()` calculates the conjugate, rather than inverting the quaternion

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#198]
The `Quaterniond` methods `invert()` and `conjugate()` have the same effect of flipping the sign of `x`, `y` and `z` (except that `invert()` also normalizes the quaternion). I think `invert()` is supposed to also flip the sign of the `w` component. (An "inverted" quaternion `q' = -q` is the same exact rotation, but going "the other way around".)

**Comment by httpdigest** [comment]
The inverse of the quaternion is correct as implemented. If you negate all components, you end up with the exact same rotation about the exact same axis. In other words, the two quaternions `(x, y, z, w)` and `(-x, -y, -z, -w)` describe the exact same orientation. This is the same as with an axis-angle representation. If you negate the axis and also the angle, you end up with the exact same rotation.

**Comment by lukehutch** [comment]
OK, is this comment wrong then?:

https://en.wikipedia.org/wiki/Slerp#Source_code

```
    // If the dot product is negative, slerp won't take
    // the shorter path. Note that v1 and -v1 are equivalent when
    // the negation is applied to all four components. Fix by 
    // reversing one quaternion.
    if (dot < 0.0f) {
        v1 = -v1;
        dot = -dot;
    }
```

Or do they just mean that `v1 = -v1` is negating only three of the four components? (Sorry for the basic question...)

**Comment by httpdigest** [comment]
This code example apparently uses an overloaded operator `-` on the Quaternion type which it does not define. So there is no way of knowing what this operator does. But my bet is that it computes the conjugate.
