### ISSUE TITLE
Method to compute (q^-1 p) or (q p^-1) directly

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#199]
I'm looking for a method to compute the following for quaternions `p` and `q`:

```
r = p q p^-1
```

The combinations `q p^-1` and `q^-1 p` seem to come up quite commonly (for the rotation between two quaternions), so it would increase efficiency if there were methods that computed these directly. (This would increase the number of multiplication methods by a factor of 3 over the current `mul` and `premul` variants -- with new variants for inverting `this` and inverting the passed parameter.) 

The JOML API lets you pre-allocate objects to avoid allocating intermediate objects, but then to compute a product with an inverted parameter, you have to pre-allocate a quaternion just to do the inversion (or deal with there being an extra intermediate object allocated). In the worst case, it is the following (I'm sure one or two of the intermediate objects could be reused with some smarter ordering of operations):

```
Quaterniond r = p.mul(q.mul(p.invert(new Quaterniond()), new Quaterniond()), new Quaterniond());
```

instead of something like

```
Quaterniond r = p.mul(q.mulByInverted(p, new Quaterniond()), new Quaterniond());
```

**Comment by httpdigest** [comment]
The various rotateXXX/rotationXXX methods in Quaternionf is probably what you want.

**Comment by lukehutch** [comment]
I need to reverse the current world model rotation (`p^-1`), then apply a new local rotation to the model (`q`), then re-apply the world rotation back to the model again (`p`). I can't see how the rotateXXX/rotationXXX methods would accomplish this.

**Comment by httpdigest** [comment]
I see, you need the "conjugate p by q" operation: https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation#The_conjugation_operation
I'll add it to JOML shortly.

**Comment by lukehutch** [comment]
Correct, thanks for clarifying. BTW I did find the `difference()` method which computes half of this, specifically the `q^-1 p` I was asking about.

**Comment by httpdigest** [comment]
Changes will be up with build https://travis-ci.org/JOML-CI/JOML/builds/609934214 on oss.sonatype.org Maven repo as a new 1.9.20-SNAPSHOT version.

**Comment by lukehutch** [comment]
Really appreciate the fast turnaround!

**Comment by lukehutch** [comment]
I came across the need to compute `r = p^-1 q p`, which is `r = q.conjugateBy(p.invert(new Quaterniond()))`.

Can you please add a method `conjugateByInverse` that computes this without the required manual parameter inversion?
