### ISSUE TITLE
Request: methods for fractional add of vector and fractional application of quaternion

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#200]
Related to (but not the same as) slerp, I need a method for scaling just the angle of a quaternion by a given factor, allowing for a single (non-slerp) quaternion to be applied to a given fractional amount. The code I have to do this is:

```java
private static Quaterniond scaleQuatRotation(Quaterniond quat, double frac) {
    AxisAngle4d axisAngle = new AxisAngle4d(quat);
    double angle = axisAngle.angle;
    if (angle > Math.PI) {
        angle -= 2.0 * Math.PI;
    }
    return new Quaterniond(new AxisAngle4d(angle * frac, axisAngle.x, axisAngle.y, axisAngle.z));
}
```

However it would be more efficient to compute this internally to JOML, supplying a "fractional multiplication" method that scales the angle of a second quaternion when multiplying by a first quaternion, e.g. 

```
prevRotation.mul(newRotation, frac, new Quaterniond())
```

Similarly I need a method that adds a fractionally scaled vector:

```java
private static Vector3d addScaledVector(Vector3d vec1,Vector3d vec2, double frac) {
    return vec1.add(vec2.mul(frac, new Vector3d()), new Vector3d());
}
```

but it would be more efficient to compute this internally to JOML using an API like

```java
prevVec.add(newVec, frac, new Vector3d())
```

These methods are important for a range of interpolation tasks.

**Comment by httpdigest** [comment]
About scaling the angle of a quaternion: You can also use slerp() for this to extrapolate the angle. In other words, you proposed scaleQuatRotation() is just a slerp() with the identity quaternion and the quaternion to scale the angle of. You can even extrapolate using factors greater than 1.0.

About adding a scaled vector: Check out Vector3f/d.fma(). "Fused multiply-add". I come to realize that this is a bad name. :)

**Comment by lukehutch** [comment]
OK, I tried slerp'ing from an identity quaternion already, but I didn't know if that was a valid thing to do, since the axis vector is zero -- so I abandoned it :-)

Yes, fma is what I was looking for -- sorry to miss that!

**Comment by httpdigest** [comment]
I'm going to add an optimized `slerpFromIdentity` anyway, because some operations can be omitted for the case where one of the quaternions is `(0, 0, 0, 1)` and it should become a tad faster.

**Comment by lukehutch** [comment]
You could use a linear or polynomial approximation for the Math.sin calls, for angles around 0 or PI.

See also this post on fast normalization of quaternions (using a fast approximation of 1/sqrt):

https://stackoverflow.com/a/12934750/3950982

**Comment by httpdigest** [comment]
This is already implemented. See the org.joml.Math class. You can enable it via `-Djoml.fastmath` and additionally `-Djoml.sinlookup` to use a very fast linearly interpolated lookup table for sin.

**Comment by httpdigest** [comment]
I was also just on the lookout for a fast atan2 approximation and found one yielding very small errors: https://github.com/JOML-CI/JOML/commit/06e4c28ba5c1af63c192d3e4740c217541d91139

**Comment by lukehutch** [comment]
Thanks for the pointer. I see that `sqrt` is not yet approximated, and there is no entry in the `Math` class for inverse `sqrt`. The inverse `sqrt` trick I linked above is very useful for quaternions when you normalize after every operation, since it is highly optimal when the magnitude of the result is already close to 1.0.

**Comment by httpdigest** [comment]
I am not sure that approximating sqrt is worth it. Assuming that the JIT lowers a `(float) sqrt()` to an x86 `SQRTSS` instruction, then this (on Skylake) has the same operation latency as `DIVSS` (which would be needed for the approximation itself). In addition, we also need the comparison (which branch prediction can probably predict well when normalizing often).

**Comment by lukehutch** [comment]
> your proposed scaleQuatRotation() is just a slerp() with the identity quaternion and the quaternion to scale the angle of.

I have run into an issue with this. For the following code:

```java
double ang = Math.toRadians(5.0);
Quaterniond identity = new Quaterniond();
Quaterniond finalRotation = new Quaterniond(new AxisAngle4d(ang, new Vector3d(0, 0, 1)));
int n = 100;
for (int i = 0; i < n; i++) {
    Quaterniond q = identity.slerp(finalRotation, i / (double) (n - 1));
    System.out.println(q.angle());
}
```

you get this curve:

![image](https://user-images.githubusercontent.com/811305/76161520-cbc48a80-60f9-11ea-826e-b9141fff21f1.png)

This does not give linear interpolation. What is the issue here?

**Comment by lukehutch** [comment]
Sorry, reopened but I found an issue in my code. Closing again.
