### ISSUE TITLE
NaN after `new AxisAngle`

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#202]
I have a quaternion `q`:

w = -1.0
x = -6.254019E-5
y = 2.4972862E-4
z = 1.8589203E-4

After calling `AxisAngle4f aa = new AxisAngle4f(q)` I get an axis with `NaN` in all components.

The problem is this line in `AxisAngle4f`, which does a division by zero:

```
float invSqrt = (float) (1.0 / Math.sqrt(1.0 - q.w() * q.w()))
```

Ironically the previous line calls `safeAcos` -- but the above line is not safe.

The quaternion was produced by calling `a.rotationTo(b, q)`, where `a` is

x = -0.4391875
y = -0.60461336
z = 0.6644975

and `b` is 

x = -0.43974409
y = -0.6045331
z = 0.6642024

although I flipped the sign on all components of `q` for consistency to solve the "quaternion double cover problem". This flipped `q.w` from `1.0` to `-1.0`. Either way though the result would still have been `NaN`.

The core problem seems to be that the `AxisAngle` constructor expects the quaternion to be normalized. However this is not even documented.

Even with normalized quaternions, however, this will fail for the normalized quaternion (0 0 0 1) (where `w` is in the last position).

**Comment by httpdigest** [comment]
Thanks! Fix is up as new 1.9.20-SNAPSHOT.
