### ISSUE TITLE
Quaternionf#angle() should use safeAcos

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#203]
`Quaternionf#angle()` should use `safeAcos`. Currently it does this:

```java
    public float angle() {
        float angle = (float) (2.0 * Math.acos(w));
        return (float) (angle <= Math.PI ? angle : Math.PI + Math.PI - angle);
    }
```

This should be

```java
        float angle = (float) (2.0 * (w < -1.0f ? Math.PI : w > +1.0f ? 0.0 : Math.acos(w)));
```

Also I think this `acos` formula expects the quaternion to be normalized (for `w` to have the half cosine interpretation), which it may not be.

Furthermore, I think the angle range correction formula is wrong? Shouldn't it be the following?:

```java
        return (float) (angle <= Math.PI ? angle : angle - Math.PI - Math.PI);
```

An angle `a1` is only rotationally equivalent to `a2` if `a1 = k * (2 * PI) * a2` for some integer `k`.

**Comment by httpdigest** [comment]
Thanks! Fix is up as new 1.9.20-SNAPSHOT.
