### ISSUE TITLE
Quaternion transform method only works with normalized quaternions

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#204]
The Quaternion method `transform` requires the quaternion to be normalized, but this is not documented.

There is a better method here, which works with unnormalized quaternions, but also avoids the sqrt (see the Java code):

https://www.euclideanspace.com/maths/geometry/rotations/conversions/quaternionToMatrix/index.htm

**Comment by httpdigest** [comment]
Thanks! I think it's best to call this a bug and fix this method and then add a new method `transformUnit` (much like the existing `transformUnitPositiveX/Y/Z`) which handles transforming a vector by this unit quaternion when we know that it's a unit quaternion.

**Comment by lukehutch** [comment]
Long term I think it is best to subclass all the Quaternion classes with Unit variants that do not expose their fields, but guarantee the quaternion is normalized.

**Comment by httpdigest** [comment]
Dont' know it subclassing is the right approach for this, but possible, yes. This is in some sense the same as the "matrix properties" of the Matrix4f/d classes to route method calls to a more optimized version when certain properties of a matrix are known. I was thinking of doing the same with quaternion, just that unit/normalized is the only (or first) tracked property.

**Comment by lukehutch** [comment]
The only problem with adding a properties fieldnis that it would increase the storage size required. I deal with enormous point clouds, and it's already a stretch to justify the Java object overhead for the luxury of using Vector3d types.

**Comment by httpdigest** [comment]
> The only problem with adding a properties field is that it would increase the storage size required

Unlikely. Object sizes are padded for 8-byte alignment anyways. Currently, on a JDK-14, a Quaternionf instance takes 32 bytes and a padding of 4 bytes (according to [JOL](https://openjdk.java.net/projects/code-tools/jol/)). Adding an additional byte makes no difference to the size.

**Comment by httpdigest** [comment]
A new 1.9.21-SNAPSHOT build is up on oss.sonatype.org with a Quaternion.transformUnit() (which works like the old Quaternion.transform()) and a modified Quaternion.transform() which works with non-unit quaternions as well.
