### ISSUE TITLE
Vector#mul(Matrix) should really be called preMul

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#205]
`Vector#mul(Matrix)` for a vector `v` and matrix `A` computes `Av`. Therefore the name should be `preMul`, not `mul`. (It's also confusing that `Matrix#transform(Vector)` is called `transform` and not simply `mul`.)

**Comment by httpdigest** [comment]
Yeah, true. `Matrix.transform` was kind of borrowed from javax.vecmath convention. And indeed, `Vector.mul(Matrix)` should have been called `premul` or the multiplication order should be made clear in the documentation.

**Comment by httpdigest** [comment]
Will be addressed in the next major version of JOML, tracked with the 2.0.0 release milestone.
