### ISSUE TITLE
Matrix element indexing notation is backwards compared to convention

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#206]
A matrix element `m32` corresponds to column 3, row 2 in the matrix. This is backwards compared to standard matrix notation, which uses `row, column` ordering.

**Comment by lukehutch** [comment]
Furthermore the `Matrix` constructor that takes e.g. 9 doubles for a 3x3 matrix expects the values to be in column-major order, but this is not documented, and it seems contrary to the current `column, row` element indexing scheme, which would seem to vaguely indicate row-major order.

**Comment by httpdigest** [comment]
https://github.com/JOML-CI/JOML/wiki/Common-Pitfalls#matrix-element-subscripts-are-column-then-row

JOML uses this convention everywhere and for obvious reasons it is not going to be changed.

**Comment by httpdigest** [comment]
I'll close this issue for now and will address it with a next major version of JOML. I think this point is valid and is likely going to be addressed in the next major version. It has the 2.0.0 release milestone, so we can keep track of it.
