### ISSUE TITLE
Quaternion classes need inverseTransform operation

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#209]
When working with quaternions, it's common to need to go back and forth between world coordinates and local coordinates. With the current JOML API, if rotations and translations are stored as quaternions and vectors respectively (rather than using homogeneous matrices), this requires frequently inverting quaternions before calling the `Quaternion#transform(Vector)` operation. It would be great if all the `transform` methods came with analogous methods `inverseTransform(Vector)` that transformed by the inverse of the quaternion, so that the quaternion doesn't have to be manually inverted to transform by its inverse.

For consistency, this sort of method could also be added for matrices, however inverting a matrix is a more heavyweight operation than inverting a quaternion, so maybe inversion should still be done by hand for matrices.

**Comment by httpdigest** [comment]
Added transformInverse() and transformInverseUnit() to Quaternionf/d.

**Comment by lukehutch** [comment]
Thanks for the incredibly fast turnaround!
