### ISSUE TITLE
Cross product bug Vector3f

### ISSUE THREAD

**Issue by ieperen3039** [JOML-CI/JOML#210]
Since a recent update, the cross product calculation behaves unexpected.

Running the following:
```java
Vector3f a = new Vector3f(0, 2, 0);
Vector3f b = new Vector3f(0, 0, 2);
Vector3f cross = a.cross(b);
```
gives `( 4,000E+0 -8,000E+0  0,000E+0)` while i would expect `( 4,000E+0  0,000E+0  0,000E+0)`

i think that the implementation of cross on line 1585 of Vector3f.java should cache the values for x and y.

**Comment by httpdigest** [comment]
Sorry about this, that's very unfortunate. Thanks for letting me know! This calls for a quick rollout of 1.9.22 very soon.
