### ISSUE TITLE
Quaternion rotateTo should normalize vectors before dot check

### ISSUE THREAD

**Issue by ieperen3039** [JOML-CI/JOML#212]
Quaternionf.rotateTo() and Quaterniond.rotateTo() use the dot product of the two given vectors to check for parallel vectors (fixing #82), but this only works with normalized vectors.
Either document that the vectors must be normalized, or always normalize both vectors. (this is also done in the Ogre library : https://bitbucket.org/sinbad/ogre/src/9db75e3ba05c/OgreMain/include/OgreVector3.h#cl-651)

**Comment by httpdigest** [comment]
Thanks for reporting!
