### ISSUE TITLE
toString method(s) fail for non-finite values

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#215]
Printing a quaternion with invalid (non-`isFinite`) components (`NaN`, `infinity`) gives:

```
(� � � �)
```

Probably vectors and matrices have the same problem, I didn't test it.

**Comment by httpdigest** [comment]
This is merely an issue with the Windows console not supporting proper Unicode characters. The NumberFormat outputs the code point `0x221E` when printing the infinity sign ∞. On a Linux terminal (as well as in the Eclipse-internal console - which is _not_ using cmd under the hood), the following code:
```java
System.out.println(new Quaternionf(Float.POSITIVE_INFINITY, Float.NaN, Float.NEGATIVE_INFINITY, Float.NaN));
```
correctly prints:
```
( ∞ NaN -∞ NaN)
```

**Comment by lukehutch** [comment]
This was in Eclipse 2019-12 on Fedora.

**Comment by lukehutch** [comment]
Might be better to use NaN and inf/infinity...

**Comment by httpdigest** [comment]
Okay, changes are in.
```java
System.out.println(new Quaternionf(1, 2, 3, 4));
System.out.println(new Quaternionf(Float.NaN, 2, Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY));
```
now produces nice non-unicode output (and also NaN/Inf are nicely column-aligned!):
```
( 1,000E+0  2,000E+0  3,000E+0  4,000E+0)
(      NaN  2,000E+0      +Inf      -Inf)
```

**Comment by lukehutch** [comment]
Nice! Thanks for the very speedy turnaround time as always.
