### ISSUE TITLE
Ambiguous return value from point/triangle intersection methods

### ISSUE THREAD

**Issue by Xayton** [JOML-CI/JOML#223]
Hi, I noticed that the static constants `POINT_ON_TRIANGLE_VERTEX_1` and `POINT_ON_TRIANGLE_FACE` share the same integer value (2). These are found both in `Intersectiond` and `Intersectionf`.

There are some methods (`findClosestPointOnTriangle`, `intersectSweptSphereTriangle`) that can return both, making impossible for the caller to tell which of the two cases it really is.

Fixing this will probably be a breaking change.

Thank you for the great library, and great support.

**Comment by httpdigest** [comment]
Thanks a lot for reporting!
