### ISSUE TITLE
Extreme garbage generation and bad performance due to emulation of fma() on older CPUs

### ISSUE THREAD

**Issue by theagentd** [JOML-CI/JOML#225]
Hello!

When running on an Intel Sandy Bridge i5-2500 CPU, we experienced extreme garbage generation (500-1000MB/sec) and unreasonably bad performance using JOML, despite the same program running fine on other CPUs. After using VisualVM's memory profiling, we tracked down the issue to the fma() instruction creating large amounts of BigInteger, MutableBigInteger, BigDecimal and FDBigInteger instances. It would seem that Sandy Bridge CPUs doesn't have a native FMA instruction, so the calculation must be emulated to provide the no-rounding guarantee of fma().

We don't need the improved precision of fma(), so it would be better if JOML fell back to simply calculating a*b+c as two instructions instead of this. Some sources, like this one [https://richardstartin.github.io/posts/autovectorised-fma-in-jdk10], suggests that manually using fma() can reduce performance by disabling automatic, possibly more optimal, vectorization, so perhaps JOML should simply not use fma().

**Comment by httpdigest** [comment]
Hi @theagentd, which version of JOML are you using?
I've tried using timing to detect whether FMA3 is actually supported by the CPU and if not then simply falling back to a*b+c. I've also tested this on a Sandy Bridge CPU.
Check out the release notes of https://github.com/JOML-CI/JOML/releases/tag/1.9.21 and https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Runtime.java#L38 .
On newer CPUs, the performance was consistently better with single instruction fma.

**Comment by princec** [comment]
Latest 1.9.23. I would strongly suggest implementing it as simply a*b+c and letting the JRE autovectorize it if it can, as it's utterly murdered performance on the Sandy Bridge. That microbenchmark to detect FMA / deduce its performance is subject to just about every scary story your grandma would have told you about the perils of microbenchmarks. In the meantime we'll hack it to always return false.

**Comment by httpdigest** [comment]
Alright, I've toggled the use of `java.lang.Math.fma()` behind the `-Djoml.useMathFma` toggle, disabled by default. I should've listened to my gut feeling about that microbenchmark as well. :)

**Comment by httpdigest** [comment]
1.9.24 is underway. Should be available on Maven Central in at most an hour.

**Comment by princec** [comment]
Many thanks Kai!

**Comment by httpdigest** [comment]
Sure. Sorry about that incident, and thank you both for discovering/investigating!

**Comment by richardstartin** [comment]
FWIW the post linked here states that `Math.fma` **can** be autovectorised by C2, since a bug was fixed in JDK10.
