### ISSUE TITLE
consider adding some simple Range classes for JOML?

### ISSUE THREAD

**Issue by XenoAmess** [JOML-CI/JOML#229]
some thing like this
https://github.com/google/guava/blob/3ba6d135439c1fa6ac80cf5ccab118c396dd402c/android/guava/src/com/google/common/collect/Range.java

but for primitive types(reducing autopackaging)

like IntRange, DoubleRange

**Comment by httpdigest** [comment]
What exactly would be the usecase in a 2d/3d engine/game for such a range/interval? Anything particular you had in mind when posting this issue?

**Comment by XenoAmess** [comment]
You asked a good question here.
After further thought about this I realise this is something that can used not only in game development  but also other development.
So It might be better to add them to guava directly.
Thx.
