### ISSUE TITLE
Feature add AABBI

### ISSUE THREAD

**Issue by pollend** [JOML-CI/JOML#234]
At the moment the library has AABBf and AABBd. I have this version of Region3i in Terasology that is suppose to replace the old Region3i. The functions and what not line up more with JOML so I believe it could be reworked and ported over to an AABBi type of shape. 

AABBi seems kind of Terasology specific so I was wondering if it would be worth implementing in JOML. 

https://github.com/MovingBlocks/Terasology/blob/5d1ec310ed76da9c08ff4fdecb0003aca444e8e1/engine/src/main/java/org/terasology/math/Region3i.java

**Comment by httpdigest** [comment]
Implementing this as AABBi sounds good to me.
