### ISSUE TITLE
Rectanglei#intersects() and AABB#testAABB() consistency

### ISSUE THREAD

**Issue by pollend** [JOML-CI/JOML#239]
for consistency would it be better to make these functions match better. Rectangle is similar enough to an AABB where these functions should follow a similar naming convention. There is also the other function Rectangle#contains where its only true if a rectangle contains another rectangle. would it be worthwhile to reconcile the names across these two classes for consistency. I could imagine AABB and Rectangle sharing a lot of the same functions.

**Comment by httpdigest** [comment]
Yes, good idea! Having consistent names across these classes (even considering an API break) is probably a good idea. I also don't think many users actually use AABB or Rectangle. So, we should change the names probably to `contains` and `intersects`.

**Comment by pollend** [comment]
for the AABB we use these functions to test intersections:
```
AABBi\d\f#testPoint
AABBi\d\f#testPlane
AABBi\d\f#testPlane
AABBi\d\f#testAABB
AABBi\d\f#testSphere
AABBi\d\f#testRay
```

do we want some similar test functions for rectangle. contains and intersects are two different cases.

**Comment by httpdigest** [comment]
All those `test*` methods are basically `intersects*`. I would be okay with renaming all `AABB.test*()` methods to `AABB.intersects*()` since all of them test whether the AABB intersects the given object (point, plane, ray, sphere, ...). Yes, `contains()` is indeed something different and I'd also like to keep it called `contains()`.

**Comment by pollend** [comment]
that sounds good.

**Comment by pollend** [comment]
https://github.com/JOML-CI/JOML/pull/240 the naming is kind of verbose but its probably easier to interpret with the more verbose name. 

```
intersect(a,b,c,d) vs intersectsPlane(a,b,c,d)
intersect(a,b,c) vs intersectsPoint(a,b,c)
```
