### ISSUE TITLE
BMesh Data Structure

### ISSUE THREAD

**Issue by pollend** [JOML-CI/JOML#241]
https://wiki.blender.org/wiki/Source/Modeling/BMesh/Design

Blender uses this data structure to describe mesh data. would it be worthwhile adding this to either another library under JOML or would it be better for this to be something entirely separate. 

Is there any interest to extend JOML into other sub libraries with some other 3d math tools? This came up in Terasology when there was a discussion about GLU.

**Comment by httpdigest** [comment]
I would really like to keep any computational geometry topics out of JOML. This should go into another library. I think that any good solution will need tight integration into a particular game or game engine and every game will likely do some customization to the algorithm and data structures to cater its specific needs. Also the solution must integrate well with the mesh loading/storing I/O mechanism.
