### ISSUE TITLE
Intersectiond.intersectLineSegmentAar : result can be out of bounds

### ISSUE THREAD

**Issue by Tynogc** [JOML-CI/JOML#252]
I have found some strange behavior in the Intersection-Methods for Line-segments with Aar/Aab.

The returned type TWO_INTERSECTIONS can be returned too often with the results being out of range(result.y > 1 or result.x < 0).

I have outlined the Problem to be within the following lines of the Intersectiond-class Lines 4503-4518:

```java 
       if (tNear < tFar && tNear <= 1.0 && tFar >= 0.0) {
            if (tNear > 0.0 && tFar > 1.0) {
                tFar = tNear;
                type = ONE_INTERSECTION;
            } else if (tNear < 0.0 && tFar < 1.0) {
                tNear = tFar;
                type = ONE_INTERSECTION;
            } else if (tNear < 0.0 && tFar > 1.0) {
                type = INSIDE;
            } else {
                type = TWO_INTERSECTION;
            }
            result.x = tNear;
            result.y = tFar;
        }
     return type;
```

Imo. the INSIDE -statement must envelop `else if (tNear <= 0.0 && tFar >= 1.0)`
Depending on expected behaviour the cases tNear = 0.0 and tFar = 1.0 can of couse also be added to the ONE_INTERSECTION clauses.
Otherwise results of tNear = 0.0 and tFar = 10000 are still processed as two intersections [which it is clearly not]

I'm of cause not sure if this is the correct solution and would therefore be grateful if you have a look.

If there is a Problem it would need the same fix in Interpolationd.intersectLineSegmentAab and the respective Methodes in Interpolationf.

**Comment by httpdigest** [comment]
Thanks a lot for reporting this! It'll be fixed in the next 1.9.26 release (or grab the latest 1.9.26-SNAPSHOT).
