### ISSUE TITLE
mulAdd documentation incorrect

### ISSUE THREAD

**Issue by Runemoro** [JOML-CI/JOML#254]
The documentation for [`Vector3d.mulAdd(double a,  Vector3dc b)`](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Vector3d.java#L853-L867) claims that `a * b` is added to the vector (`this = this + a * b`), while actually, the vector is first multiplied by `a` and then `b` is added to it (`this = this * a + b`).

**Comment by httpdigest** [comment]
Thank you!
