### ISSUE TITLE
new AxisAngle4d().set(new Quaterniond()) gives NaN for axes

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#255]
The following code

```
var a = new AxisAngle4d();
var q = new Quaterniond();
a.set(q);
```

gives

```
a.x == NaN
a.y == NaN
a.z == NaN
a.angle == 0.0
```

I would expect the axes of `a` to be zero, not `NaN`, since the axes of `q` are zero.

**Comment by httpdigest** [comment]
Thanks! The case of identity quaternion should be fixed now.

**Comment by lukehutch** [comment]
Thanks for the quick fixes, as always!
