### ISSUE TITLE
JOML needs Quaternion.mulInverse() and Quaternion.premulInverse() methods

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#258]
Currently calculating `q1 = q2.mul(q3.inverse(new Quaterniond()))` and `q1 = q3.premul(q2.inverse(new Quaterniond()))` is inefficient. There should be specific methods for this, since it is such a common operation (to find the rotational difference between two quaternions).

**Comment by httpdigest** [comment]
I think you mean https://javadoc.io/static/org.joml/joml/1.9.25/org/joml/Quaternionf.html#difference-org.joml.Quaternionf-
It's aptly called "difference". :)

**Comment by lukehutch** [comment]
That's the one! I skimmed through all the methods at least three times looking for this, and didn't find it -- not sure why this didn't jump out to me as obviously already implemented. Thanks!
