### ISSUE TITLE
Math.atan2 used in Quaternion.slerp() is slow

### ISSUE THREAD

**Issue by lukehutch** [JOML-CI/JOML#261]
I have an application that does a lot of `Quaterniond.slerp()` operations. I couldn't figure out why it was so slow, so I profiled it:

![image](https://user-images.githubusercontent.com/811305/90203029-bf291a00-dd9c-11ea-8d80-635c65088539.png)

I had no idea `Math.atan2()` was so slow.

Is there a possibility of switching to a fast approximation?

https://math.stackexchange.com/questions/1098487/atan2-faster-approximation

**Comment by httpdigest** [comment]
Is there a reason why you created two identical issues and closed only one of the?
https://github.com/JOML-CI/JOML/issues/262

**Comment by lukehutch** [comment]
No, I definitely only created one issue. This must have been a GitHub hiccup, or the browser submitted the form twice for some reason. Sorry about that.
