### ISSUE TITLE
Math.signum

### ISSUE THREAD

**Issue by pollend** [JOML-CI/JOML#267]
I would like a function that just provides the sign of the number. 

```
Math.signum(1.2f) == 1.0f
Math.signum(-1.2) == -1.0f
Math.signum(4) == 1
Math.signum(-4) == -1
```

**Comment by httpdigest** [comment]
So, you mean a facade for java.util.Math.signum() and java.lang.Integer/Long.signum(), because java.util.Math.signum() only provides overloads for float and double?

**Comment by pollend** [comment]
I guess a facade is what I'm asking about. it get a bit problematic when I have to import java.util.Math and org.joml.Math.
