### ISSUE TITLE
Add library into Maven.

### ISSUE THREAD

**Issue by Wolftein** [JOML-CI/JOML#27]
It would be awesome to add this library into maven, so people can easily link using Grandle or Maven!.

**Comment by httpdigest** [comment]
I totally agree.
However, every time I try to tackle that issue, I find myself deeper and deeper into stackoverflow entries about a good, working approach of deploying to sonatype's Maven Central.
And boy, they do not make it easy at all. :)
However, if you have the knowledge of how to do this properly, you are very welcome to change JOML's pom.xml and make a Pull Request.

For the time being JOML's users can download the JAR from GitHub Release and deploy it manually into their local repository via:
`mvn install:install-file -Dfile=JOML.jar -DgroupId=org.joml -DartifactId=JOML -Dversion=1.3.1-SNAPSHOT -Dpackaging=jar`

The pom is then auto-generated but that is not too bad as JOML currently does not have any runtime-time dependencies to other libraries.

**Comment by httpdigest** [comment]
I am happy to say, that JOML's current version 1.3.3-SNAPSHOT is now deployed on oss.sonatype.org!
Have fun! ;)

**Comment by Wolftein** [comment]
Hi!, i'm currently having some trouble to link the library, it cannot find the library in the sonartype snapshots maven.
```
        repositories {
        maven {
            url 'http://oss.sonatype.org/content/repositories/snapshots'
        }
        } 
     
       dependencies {
          compile 'org.joml:joml:1.3.4-SNAPSHOT'
       }
```
