### ISSUE TITLE
Why not implement cloneable interface for vector and matrix?

### ISSUE THREAD

**Issue by zhouhang95** [JOML-CI/JOML#279]
As, title.

**Comment by XenoAmess** [comment]
Cloneable is not recommended.

**Comment by httpdigest** [comment]
There is no reason, why the classes currently didn't implement Cloneable. There simply wasn't anyone asking for it, until now.
Added with https://github.com/JOML-CI/JOML/commit/223693611854b5c6001533a36a92bf39cef320bf

**Comment by zhouhang95** [comment]
Thank you.
I think it's more handy that "p.clone()" in palce of "new Vector3f(p)".
