### ISSUE TITLE
how can use ray intersect plane?

### ISSUE THREAD

**Issue by qq1053831109** [JOML-CI/JOML#284]
how can use ray intersect plane?

**Comment by httpdigest** [comment]
What do you mean?
https://github.com/JOML-CI/JOML/blob/main/src/org/joml/Intersectionf.java#L985

**Comment by qq1053831109** [comment]
i need this in joml:
    /**
     * 
     * @param p
     * @param loc
     * @return true if the ray collides with the given Plane
     */
    public boolean intersectsWherePlane(Plane p, Vector3f loc) {
        float denominator = p.getNormal().dot(direction);

        if (denominator > -FastMath.FLT_EPSILON && denominator < FastMath.FLT_EPSILON) {
            return false; // coplanar
        }
        float numerator = -(p.getNormal().dot(origin) - p.getConstant());
        float ratio = numerator / denominator;

        if (ratio < FastMath.FLT_EPSILON) {
            return false; // intersects behind origin
        }
        loc.set(direction).multLocal(ratio).addLocal(origin);

        return true;
    }

**Comment by qq1053831109** [comment]
this is ray
