### ISSUE TITLE
Obtaining/Building a JAR?

### ISSUE THREAD

**Issue by gmseed** [JOML-CI/JOML#291]
I downloaded the zipped code from Github and saw a pom.xml and ran it with mvn package and got the error: "... Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project joml: Cannot get the revision information from the scm repository : [ERROR] Exception while executing SCM command.:  ..." and appears to assume git is pre-installed.

I then popped over to your website and downloaded the zip in the header and surprised to see it contains no source code and only html files.

All I want to do is to be able to include a jar in order to try out a lwjgl demo !

**Comment by pollend** [comment]
you can download the jar directly from sonatype: https://search.maven.org/search?q=g:org.joml%20a:joml

**Comment by httpdigest** [comment]
There are also the classes and sources jars under "Assets" in each GitHub Release. See: https://github.com/JOML-CI/JOML/releases
