### ISSUE TITLE
Request: AABBd and AABBf .set(x1,y1,z1, x2,y2,z2)

### ISSUE THREAD

**Issue by jordan4ibanez** [JOML-CI/JOML#294]
This is a simple request to reuse AABB(f and d) objects without needing to call the:
.setMin(x1,y1,z1) and .setMax(x2,y2,z2)

So it can be cleanly reused by just simply doing .set(x1,y1,z1,x2,y2,z2)

**Comment by httpdigest** [comment]
There is no AABB in main JOML anymore, as of JOML 1.10.0. All the geometric primitives has been moved to [joml-primitives](https://github.com/JOML-CI/joml-primitives/issues). See: https://github.com/JOML-CI/JOML/releases/tag/1.10.0
Also, I am not sure what you mean by "reuse". You can certainly call: `aabb.setMin(x, y, z).setMax(x, y, z)`. I don't see a strict necessity for having a "merged" method like you proposed.
