### ISSUE TITLE
Where is Planed?

### ISSUE THREAD

**Issue by charlesritchea** [JOML-CI/JOML#295]
Trying to upgrade to the latest from 1.9.x and Planed is gone. What am I suppose to use instead now?

**Comment by httpdigest** [comment]
Please read the release notes of the releases you are upgrading to.

**Comment by charlesritchea** [comment]
@httpdigest I did, I don't see Planed mentioned anywhere, sorry if I'm dense. I'm dealing with legacy code, not really familiar with the library

**Comment by charlesritchea** [comment]
I guess you mean the primitives stuff

**Comment by SWinxy** [comment]
`Planed.java` (along other primitives) was moved to [JOML-CI/joml-primitives](https://github.com/JOML-CI/joml-primitives) in [1.10.0](https://github.com/JOML-CI/JOML/releases/tag/1.10.0).
