### ISSUE TITLE
Investigate SSE JIT support for JOML

### ISSUE THREAD

**Issue by httpdigest** [JOML-CI/JOML#30]
Investigate the possibility to use native code (SIMD instructions specifically) for a sequence of Matrix4f operations. This would probably allow matrix operations to be executed faster.

**What is the motivation behind this?**
Increase performance by making use of SIMD instructions for matrix operations.

**Limitations with the JVM**
Any native code, that a high-performance library such as JOML wants to use, will suffer tremendously from JNI's latency. An example is libGDX, which implements its matrix methods as native code and because of this is 2x slower than JOML.

**Possible solution**
The only way to get rid of the JNI overhead is to *hide* it. That means, a JNI function must do enough work *faster* than Java code could do it. Instead of providing JNI methods for each of the individual JOML matrix functions, we would need to *batch*/*record*/*journal* as many of the matrix operations as possible as they are invoked by client code on a Matrix4f instance.
A typical usecase of JOML could be: `m.perspective(...).lookAt(...).mul(matrix).invert().get(fb)`.
Of course this fluent interface style of writing the operations is purely syntactical sugar, but it illustrates that for this enhancement to possibly succeed, there must be a static sequence of Matrix4f method calls in the client code that can be recorded as they happen for further batch-processing later on.
Journaling and lazily evaluating those operations works because:
- a) all Matrix4f methods operate on *this*,
- b) most of the Matrix4f methods actually do not allow their effects to be visible by client code, other than the client code actually reading the Matrix4f fields in-between those operations, and
- c) the most likely usecase of JOML is that of a modern OpenGL application where the client does not want to transform `Vector4f` instances by a matrix but do some sequence of matrix transformations and finally upload the resulting matrix to OpenGL to be used by the fixed-function or the shader pipeline.

The methods that *do* allow to inspect the state of an operation, such as `Matrix4f.get(FloatBuffer)` would need to be declared as *terminal operations*.
There, the batching/journaling of matrix operations on a particular Matrix4f instance would need to end.

**What happens after journaling is ended?**
After client code executed a sequence of matrix operations on a particular Matrix4f object for the first time and then invoked a terminal operation, that Matrix4f instance needs to change its state from *not terminated* to *terminated*.
Additionally the recorded operations in the journal are now being read and translated to native code, using some templated SSE code for each operation.
After that termination happened, subsequent invocations of the same sequence of methods on that Matrix4f instance will not journal those operations anymore but instead use the JIT'ted native function to evaluate the whole sequence with one native function call at once.

**How do we access actual arguments?**
The actual arguments to the sequenced matrix operations can be buffered into a direct ByteBuffer held by the Matrix4f instance. Once the terminal operation is executed, this ByteBuffer is being used by the JIT'ted code to read off all actual arguments.
The JIT'ted native code would need to know the offsets of course for that to happen, which are written during the code generation when the terminal operation is executed the first time.

**How do we store the matrix elements?**
Accessing the 16 float fields would be too slow. We should store those fields directly in off-heap memory accessible as `float*` by the native code. The native code would therefore need to have a `float[16]` array for each terminated Matrix4f instance to still allow multithreading.
The cost is that client code would therefore not be able to inspect the state of a Matrix4f anymore by accessing the individual float fields.

**Problems with this approach**
Since we introduce state, impose usage restrictions and also generate native code using operating system functionality, which is not lightweight, there is a high potential for misuse of JOML, which will likely lead to high memory usage and poor overall performance. This can be because client code allocates new Matrix4f objects for each *frame* or because there are multiple terminal operations executed on the same Matrix4f object.

**Restrictions**
- how to resolve calling multiple terminated sequences on the same matrix?
- how to ensure that always the same sequence of operations is called on a given matrix? (i.e. client code with branches calling different matrix methods on different conditions is problematic)

**Corner points:**
- [how to build a simple JIT](http://blog.reverberate.org/2012/12/hello-jit-world-joy-of-simple-jits.html)
- [how to encode SSE x86 in C](http://luajit.org/dynasm.html)
- [allocate executable memory on Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366887%28v=vs.85%29.aspx)
- [SIMD instruction set](http://www.songho.ca/misc/sse/sse.html)
- [Great example of how to use DynASM](https://corsix.github.io/dynasm-doc/tutorial.html)
- [Another great example of DynASM](http://www.corsix.org/content/first-dynasm-example)

**Comment by httpdigest** [comment]
A possible interface for a new `NativeMatrix4f` could look like the following:
```Java
public class NativeMatrix4f {
    private boolean terminated;
    private long id;
    private int sequence;
    private ByteBuffer operations;
    private ByteBuffer arguments;

    private static final native long alloc();
    private static final native void callSequence(long id, int sequence);

    public NativeMatrix4f perspective(float fov, float aspect, float near, float far) {
        // ...
    }
    public NativeMatrix4f lookAt(float eyeX, float eyeY, float eyeZ, float centerX, ...) {
        // ...
    }
    public NativeMatrix4f get(FloatBuffer dest) {
        // obtain address of dest
        get(id, thatAddress);
        return this;
    }
}
```
The existing methods `perspective`, `lookAt` would have the same signature, but their implementation would differ in that the new implementation needs to journal the operations including the arguments into a given ByteBuffer. And if the matrix has not yet been terminated, it would also journal the operations.
The terminal operation `get(FloatBuffer)` would obtain the matrix elements using a native function.

**Comment by httpdigest** [comment]
**GCC/msvc inline assembly and interpreters**

The aboe outlined solution would be a classical JIT, where we generate a single code segment representing a single native function.
For multiple operation sequences we would therefore allocate multiple memory regions and the memory grows roughly linearly in the number of Matrix4f instances and call sequences we have.

There is however also the possibility to build a classical interpreter first, using inline assembly to make use of SSE.
This would mean that we cannot have a single function for each sequence of matrix operations anymore but would have a normal switch-case interpreter, that loops over all opcodes and executes the corresponding code defined via inline assembly.

A switch-case interpreter like that would be a good first solution, since it would not require us to jit code using DynASM.
That means matrix operation sequences do not allocate memory. It would however also mean that we need to run over each opcode ByteBuffer for every invocation and interpret the containing opcodes.

**Comment by httpdigest** [comment]
Played a bit with DynASM and got a simple SSE broadcast suffle instruction to work on a Vector4f:
```C
  | movaps xmm0, [rcx]
  | shufps xmm0, xmm0, 0x0
  | movaps [rcx], xmm0
  | ret
```
This is just the simplest possible thing I could come up with to test whether runtime code generation works with DynASM. And it does!
The best article about using DynASM with a working example (work with the current DynASM version) I found so far is: http://www.corsix.org/content/first-dynasm-example

Just had to read a bit about System-V x64 calling conventions... Interesting stuff there.
Now this DynASM code expects a function signature where the first parameter is a 16-byte aligned pointer storing 4 single-precision floating-point values and then broadcasting the first element to the other three. So the JNI code will `_aligned_malloc` the vector and also the matrix float array to 16 byte boundaries.

This all works with a simple JNI function that does the code generation which then stores the generated function in an internal function pointer associated with the Vector4f instance.

**Comment by httpdigest** [comment]
Good news!
I implemented code generation for Matrix4f.mul(Vector4f) using SSE (movaps, shufps, mulps and addps), and even for a single invocation doing a single matrix*vector with a single JNI invocation, that JNI version is already 8% faster than the Java version!
I just imagine how much faster a Matrix4f.mul(Matrix4f) can be and even multiple batched invocations.
This also seems like that libGDX compiled native code does not make use of auto-vectorization of SSE instructions, because libGDX's native code itself uses scalar operations.

**Comment by gouessej** [comment]
Don't make SSE a requirement except if you like planned obsolescence. I know that the vast majority of the hardware currently available supports it.

**Comment by httpdigest** [comment]
You are right. Having a native library and even using SSE should not be a requirement at all.
It will totally be optional and I guess the API will also be implemented by different classes. So as long as one does not use/invoke those classes and do not force a loading of the shared library, everything should be fine. :)

**Comment by gouessej** [comment]
Maybe there is a way of detecting SSE at runtime in Java. You can detect it at compile time when using GCC:
__SSE__
__SSE2__
__SSE3__
__AVX__
__AVX2__

**Comment by httpdigest** [comment]
Yepp, there is a way of detecting it even at runtime via the cpuid assembly instruction, and I am planning to use this.

**Comment by httpdigest** [comment]
**Current status**
I have implemented a bunch of SSE assembly methods for the most common matrix operations, such as mul(), in the following way:
- each operation is emitted only once and jumped to (threaded code)
- each operation reads the input and output matrices from main memory (by dereferencing the long address stored in the Java 'arguments' ByteBuffer, which points to another ByteBuffer holding the matrix elements)
- each operation at the end stores the final computed 4 matrix columns back into main memory (again by deferencing into the 'arguments' ByteBuffer to get the address of the destination buffer)

Some tests with other assembly code, notably that generated by GCC, which uses more main memory accesses (32) compared to JOML's handwritten code (20) showed that performance of SSE code is always limited by main memory accesses, even a L1 cache hit.

The most benefit we would therefore get by trying to keep all values in registers. If the output matrix of an operation A is the same as the input matrix of operation B then we should not spill the matrix out into main memory and load it back from there, but instead keep it in registers.
This is however difficult, since we have to keep 16 doubleword values in registers while still allowing the most register-pressured operation Matrix4f.mul() to perform correctly. That operation alone currently makes use of all 8 XMM registers to avoid main memory accesses as much as possible.

However, on x64 we do have the general purpose registers rax, rcx, rdx and r8 through r15, which are doubleworld registers. r8 through r15 (which are 8 registers in total) would therefore suffice to hold a single matrix.
This leaves us rax, rcx and rdx to do other things. Those other things are:
- rcx is our "arguments" ByteBuffer parameter
- rdx is currently used to store the jump address for our dynamic labels for threaded code

Now, we have one single register left, rax, which we currently don't need.

**Comment by httpdigest** [comment]
**More registers**
It turns out that we have more registers than I initially expected. [This wikibooks site](https://en.wikibooks.org/wiki/X86_Assembly/16_32_and_64_Bits) tells us that all x86 processors with 64 bit mode support SSE2, which includes our XMM0-XMM7 registers.
But it also tells that with the support of SSE3 we get another set of 8 SIMD registers named XMM8-XMM13. Voilà, problem of how to store a matrix permanently is solved.
And SSE3 has been supported by Intel processors since the Pentium 4 Prescott family back in 2004. So JOML will definitely can have this as a requirement when using the native execution engine. :)

**Comment by httpdigest** [comment]
**Conclusion**
After having implemented some amount of relevant and frequently used matrix methods as SSE native functions, all in all that solution only performed about 0.05 times as fast as the classic Java-only solution in JOML. The main reason for the slowdown was putting the actual arguments of the method calls into the NIO ByteBuffer to be accessible by JNI and the apparent slowdown of off-heap memory reads, which are indeed optimized by the JVM to pure register accesses when using pure Java solutions.
This memory access latency lead to the JNI version being significantly slower in the end than the Java-only solution.
Regarding JOML it does not seem possible to increase its performance via native code, since we cannot get away of passing the arguments via off-heap memory accesses.
Therefore I close this issue.
