### ISSUE TITLE
Jar Setup similar to LWJGL?

### ISSUE THREAD

**Issue by extorc** [JOML-CI/JOML#301]
How can I setup JOML in a similar way as LWJGL by adding some jar files to my build path libraries?

**Comment by httpdigest** [comment]
JOML is both published as a Maven/Gradle artifact to Maven Central and OSS Sonatype Snapshot repository (exactly like LWJGL) and is downloadable via a simple jar file under various links, such as:
- [JOML's GitHub Releases Page](https://github.com/JOML-CI/JOML/releases) (see under "Assets" in a particular release)
- [Maven Central link](https://repo.maven.apache.org/maven2/org/joml/joml/1.10.2/) (for final releases)
- [OSS Sonatype Snapshot Repository link](https://oss.sonatype.org/content/repositories/snapshots/org/joml/joml/1.10.3-SNAPSHOT/) for snapshot builds
- [the LWJGL 3 customize page](https://www.lwjgl.org/customize) (see the "Addons" section there)
- [the JOML GitHub Wiki page](https://github.com/JOML-CI/JOML/wiki) showing how to setup Maven or Gradle with JOML as a dependency

In my opinion, it is _really_ hard to miss how to download or use JOML.
