### ISSUE TITLE
Separate View Matrix and Projection Matrix

### ISSUE THREAD

**Issue by extorc** [JOML-CI/JOML#302]
In the `README.md` example for camera creation the provided code is 
```java
Matrix4f m = new Matrix4f()
     .perspective((float) Math.toRadians(45.0f), 1.0f, 0.01f, 100.0f)
     .lookAt(0.0f, 0.0f, 10.0f,
             0.0f, 0.0f, 0.0f,
             0.0f, 1.0f, 0.0f);
// the camera transformation is now in m
```
Here we are keeping perspective projection and view matrix in the same `Matrix4f` which means we cannot exclusively access View matrix.
<br>Is there a way i can have a 
```java
Matrix4f m = new Matrix4f()
    .perspective((float) Math.toRadians(45.0f), 1.0f, 0.01f, 100.0f);
```
and <br>
```java
Matrix4f m = new Matrix4f() .lookAt(0.0f, 0.0f, 10.0f,
             0.0f, 0.0f, 0.0f,
             0.0f, 1.0f, 0.0f);
// the camera transformation is now in m
```
<br> And later they may be combined in the GLSL shader.
**This mechanism doesnot work**

**Comment by extorc** [comment]
With View and Projection in same matrix.
![image](https://user-images.githubusercontent.com/66661460/139520671-fc806c0e-e13d-427f-b5bd-69c5e2dbb581.png)
With separated matrices and passed to shader and multiplied.
![image](https://user-images.githubusercontent.com/66661460/139520711-e740c2b9-28a3-49d3-bd17-ba53fa4ea478.png)
```glsl
#version 400 core

in vec3 position;
in vec2 tCords;
in vec3 normal;

out vec2 o_tCords;
out vec3 surfaceNormal;
out vec3 toLightVector;

uniform mat4 t;
uniform mat4 p;
uniform mat4 v;

uniform vec3 Lightposition;

void main(){
	gl_Position =  v * p * t * vec4(position, 1.0);
	o_tCords = tCords;

	surfaceNormal = (t * vec4(normal,0.0)).xyz;
	toLightVector = Lightposition - (t * vec4(position, 1.0)).xyz;
}
```
Data passed into shader
```java
shader.SetUniformMat4("p", camera.pMatrix);
		shader.SetUniformMat4("v", camera.vMatrix);
		shader.SetUniformMat4("t", mMatrix);
```
Matrices
```java
	public Matrix4f pMatrix = new Matrix4f().perspective((float) Math.toRadians(10.0f), 16.0f/9.0f,0.1f, 1000f);
	public Matrix4f vMatrix = new Matrix4f().lookAt(0, 0, 10, 0, 0, 0, 0, 1, 0);
```

**Comment by extorc** [comment]
@httpdigest 
With View and Projection in same matrix.
![image](https://user-images.githubusercontent.com/66661460/139520671-fc806c0e-e13d-427f-b5bd-69c5e2dbb581.png)
With separated matrices and passed to shader and multiplied.
![image](https://user-images.githubusercontent.com/66661460/139520711-e740c2b9-28a3-49d3-bd17-ba53fa4ea478.png)
```glsl
#version 400 core

in vec3 position;
in vec2 tCords;
in vec3 normal;

out vec2 o_tCords;
out vec3 surfaceNormal;
out vec3 toLightVector;

uniform mat4 t;
uniform mat4 p;
uniform mat4 v;

uniform vec3 Lightposition;

void main(){
	gl_Position =  v * p * t * vec4(position, 1.0);
	o_tCords = tCords;

	surfaceNormal = (t * vec4(normal,0.0)).xyz;
	toLightVector = Lightposition - (t * vec4(position, 1.0)).xyz;
}
```
Data passed into shader
```java
shader.SetUniformMat4("p", camera.pMatrix);
		shader.SetUniformMat4("v", camera.vMatrix);
		shader.SetUniformMat4("t", mMatrix);
```
Matrices
```java
	public Matrix4f pMatrix = new Matrix4f().perspective((float) Math.toRadians(10.0f), 16.0f/9.0f,0.1f, 1000f);
	public Matrix4f vMatrix = new Matrix4f().lookAt(0, 0, 10, 0, 0, 0, 0, 1, 0);
```

**Comment by httpdigest** [comment]
The problem is your (wrong) multiplication order in the shader:
```glsl
gl_Position =  v * p * t * vec4(position, 1.0);
```

It should be:
```glsl
gl_Position =  p * v * t * vec4(position, 1.0);
```
With JOML you also wouldn't do: `new Matrix4f().lookAt(...).projection(...);`.
It's basically the same in JOML as in GLSL: Vectors are column vectors and matrix/vector multiplications are: `matrix * vector`, hence it is: `projectionMatrix * viewMatrix * modelMatrix * modelPosition`.

**Comment by extorc** [comment]
Yup, that works. Thanks.
