### ISSUE TITLE
Java vectorization interface (JVI) 

### ISSUE THREAD

**Issue by jduke32** [JOML-CI/JOML#31]
http://people.apache.org/~xli/papers/npc10_java_vectorization.pdf

**Comment by httpdigest** [comment]
Thanks. I know those papers about vectorizing Java.
But: they do not apply to date and they probably will not be implemented in the foreseeable future by the most populer JVM: HotSpot.
Also the JVM in which that could have been implemented, Apache Harmony, is discontinued as of 2011.

**Comment by httpdigest** [comment]
Closed, because not relevant for JOML.
