### ISSUE TITLE
Kotlin extensions are not involved in the final artifact

### ISSUE THREAD

**Issue by Peanuuutz** [JOML-CI/JOML#320]
I saw there are two files for kotlin extensions, but when I actually add joml to my project they don't show up. I'm guessing they are not properly set up because kotlin sources require some stand-alone process to build.

**Comment by httpdigest** [comment]
Thanks for reporting it.
I am actually in the midst of migrating the build system from Maven to Gradle.
With it, I would then also use the Gradle Kotlin Plugin to build the Kotlin files under src/main/kotlin alongside the Java files for the JVM target.
Actually, those Kotlin files were never really tried/tested, which will change now. So, Kotlin usage should definitely improve a lot in the near future.

**Comment by httpdigest** [comment]
@Peanuuutz there is now a new 1.10.6-SNAPSHOT on oss.sonatype.org. Can you try it with that new snapshot version?

**Comment by Peanuuutz** [comment]
> @Peanuuutz there is now a new 1.10.6-SNAPSHOT on oss.sonatype.org. Can you try it with that new snapshot version?

Can confirm it's included. 😄

**Comment by Peanuuutz** [comment]
Also this feature would be nice: `componentX()` function to vector types like the following:
```kotlin
operator fun Vector2fc.component1(): Float = x()

operator fun Vector2fc.component2(): Float = y()
```
So that users can do:
```kotlin
val (x, y) = vector
```

**Comment by httpdigest** [comment]
I'd gladly accept a pull request from you if you want to make changes to the Kotlin files. I am not that familiar with Kotlin or what's even possible here.
