### ISSUE TITLE
Matrix4f.getEulerAnglesYXZ 

### ISSUE THREAD

**Issue by icedevjp** [JOML-CI/JOML#325]
Matrix4f has defined methods `getEulerAnglesXYZ` `getEulerAnglesZYX` but for some reason `YXZ` variant is missing. Is there any specific reason?

I get it indirectly from quaternion via matrix->getNormalizedRotation->getEulerAngles now, but it would be cool to have it directly in Matrix4f.

**Comment by httpdigest** [comment]
Sure. This method is now implemented in the matrix classes. Usable on the latest 1.10.6-SNAPSHOT build on oss.sonatype.org.
Though I am realizing that the convention of "returning the angle around X, Y and Z always in the vector's respective X, Y and Z fields" (regardless of the rotation order) is not useful when wanting to compute proper Euler angles that rotate only around two angles, like XZX, XYX, YXY, etc. I will probably introduce new methods for that convention to not break the existing methods.
