### ISSUE TITLE
A simpler way to create a Vector2d from a Vector3d

### ISSUE THREAD

**Issue by xupwup** [JOML-CI/JOML#336]
I'd like to have an easier way to get a lower dimension vector from a higher dimension vector. Usually from 3 dimensions to two, but from 4 to 3 too.

Currently, the only way to do this is the following:
```java
Vector3d a = new Vector3d(1, 2, 3);
Vector2d b = new Vector2d(a.x, a.y);
```

I'd like to have something like in GLSL:

```java
Vector2d b = a.xy(); // the one you need 9 times out of 10
Vector2d c = a.xx();
Vector2d d = a.zy();
```

This mainly helps when the vector3d is obtained via a long function chain:

```java
Vector3d a = getDirectionOfSomethingDifficult().cross(getOtherThing());
Vector2d b = new Vector2d(a.x, a.y);
double lengthIn2d = b.length();
```

**Comment by httpdigest** [comment]
We could do this, but given that JOML wants to stay allocation-free, we would have to make it like this:
```java
Vector2d b = a.xy(new Vector2d());
```
(of course this `new Vector2d()` can be another variable declared and allocated somewhere else)

**Comment by xupwup** [comment]
That would be a great improvement. Alternatively, maybe you could return it as a view on the data? (though Vector2dc)

**Comment by httpdigest** [comment]
> EDIT: never mind, a view also requires you to allocate something.
Initially, I thought that you meant that every Vector3d should also be a Vector2dc. :)
But that would invalidate LSP (e.g. changing the `z` component on the Vector3d would result in a different result for Vector2dc's length().

**Comment by xupwup** [comment]
No, my idea was just bad :D 
But Vector3d.xy(new Vector2d()) would be great. Could you also make Vector3d.xy(new Vector2f()) work? And Vector3f.xy(new Vector2d()) and Vector3f.xy(new Vector2f())?

**Comment by httpdigest** [comment]
But would adding these "swizzle" methods really justify bloating the classes/jar up? I mean, theoretically, people could then ask for all sorts of other 4d to 3d swizzles, etc, including vector4.xxx(vector3d), etc.
I am not thaaat convinced that writing `Vector2d xy = new Vector2d(xyz.x(), xyz.y())` is thaaat much of a burden.

**Comment by xupwup** [comment]
No, I think all the swizzles don't add that much value. But truncating a 3d vector to a 2d vector is quite common in our codebase.

Another suggestion: why not add it to Vector2d's constructor? Like this:

```java
class Vector2d {
   public Vector2d(Vector3d v) {
      x = v.x;
      y = v.y;
   }
}
