### ISSUE TITLE
Vector3d.div() incorrectly takes in Vector3d instead of Vector3dc

### ISSUE THREAD

**Issue by theagentd** [JOML-CI/JOML#339]
Tiny bug I stumbled upon today.

```Java
    public Vector3d div(Vector3d v) {
        this.x = x / v.x();
        this.y = y / v.y();
        this.z = z / v.z();
        return this;
    }
```

This function does not modify v, so it should be taking in a Vector3d**c**. :)

**Comment by httpdigest** [comment]
Hi @theagentd,
this (and other occurrences) have already been fixed with https://github.com/JOML-CI/JOML/commit/03cbd5e3bb23771b3c1f76630b7a4a847da94444 (though not released yet).
