### ISSUE TITLE
Long counterpart to integer components

### ISSUE THREAD

**Issue by jordan4ibanez** [JOML-CI/JOML#340]
I just randomly realized that the integral components do not have long counterpart components. As in for Vector3f we have Vector3d. So in this scenario it would be Vector3i and Vector3L. I'm curious on your thoughts, Kai. Let me know if this is a horrible idea in your opinion. Or if anyone else wants to chime in and tell me if this is a horrible idea. Thanks.

**Comment by httpdigest** [comment]
Added Vector4L and Vector4Lc in latest commit. Available as 1.10.6-SNAPSHOT maven artifact from oss.sonatype.org.

**Comment by jordan4ibanez** [comment]
Welp, I see no need to keep this up, you read my mind. Nice job.
