### ISSUE TITLE
Quaternionf fromAxisAngleDeg angle parameter description discrepancy

### ISSUE THREAD

**Issue by NicBOMB** [JOML-CI/JOML#342]
Quaternionf fromAxisAngleDeg is described as:
https://github.com/JOML-CI/JOML/blob/75d60fdad423942d14b2a5c1ca214f51df79bc7a/src/main/java/org/joml/Quaternionf.java#L972-L973
and it does convert `angle` to radians, but its parameter description reads:
https://github.com/JOML-CI/JOML/blob/75d60fdad423942d14b2a5c1ca214f51df79bc7a/src/main/java/org/joml/Quaternionf.java#L982

**Comment by httpdigest** [comment]
Thanks for pointing it out!
