### ISSUE TITLE
Using JOML without Kotlin

### ISSUE THREAD

**Issue by Martomate** [JOML-CI/JOML#349]
The latest version (1.10.6) has a dependency on the Kotlin standard library. This can be seen here: https://mvnrepository.com/artifact/org.joml/joml/1.10.6
https://repo1.maven.org/maven2/org/joml/joml/1.10.6/joml-1.10.6.pom

Is that an intentional change or is there some way to use JOML without it?

**Comment by httpdigest** [comment]
Sorry about that. This is by accident. For the new version 1.10.6 I changed the build process from Maven to Gradle, and wasn't paying close attention to the effective pom.xml that the Gradle build/publish generates.
I will look into this and publish a new version without this dependency.

**Comment by httpdigest** [comment]
New version **1.10.7** with no changes other than removal of the compile-time dependency on the Kotlin Stdlib Jar is published to Maven Central and should be available in the next few hours.

**Comment by Martomate** [comment]
Thank you for the quick response! I can confirm that it works as expected now.
