### ISSUE TITLE
JOML 1.10.7 no longer works with OSGI

### ISSUE THREAD

**Issue by nroduit** [JOML-CI/JOML#351]
The packaging of version 1.10.7 has lost the information needed to work with OSGI. Following this change, it is no longer possible to have JOML directly as an OSGI bundle.

MANIFEST.MF 1.10.7:
``` 
Manifest-Version: 1.0

```

MANIFEST.MF 1.10.5:
```
Manifest-Version: 1.0
Created-By: Maven Jar Plugin 3.2.0
Build-Jdk-Spec: 11
Implementation-Title: JOML
Implementation-Version: 1.10.5
Implementation-Vendor: JOML
Bundle-ManifestVersion: 2
Bundle-Name: JOML
Bundle-SymbolicName: org.joml
Bundle-Version: 1.10.5
Export-Package: org.joml,org.joml.sampling
Implementation-Build: 82538cc2678d60e5716292e0a58ff8dec7cc8cec

```

**Comment by httpdigest** [comment]
Sorry about that. A new release 1.10.8 has been published and will be ready on Maven Central within the next few hours.
