### ISSUE TITLE
Incorrect formula in Quaternionf.get(Matrix4)

### ISSUE THREAD

**Issue by sriharshachilakapati** [JOML-CI/JOML#36]
The formula for Quaternionf.get(Matrix4) is incorrect, you are actually generating a RHS matrix (the one that DirectX uses). You have to transpose it to get the correct matrix for use with OpenGL. This is what you are using.

```java
dest.m00 = 1.0f - q11 - q22;
dest.m01 = q01 + q23;
dest.m02 = q02 - q13;
dest.m03 = 0.0f;
dest.m10 = q01 - q23;
dest.m11 = 1.0f - q22 - q00;
dest.m12 = q12 + q03;
dest.m13 = 0.0f;
dest.m20 = q02 + q13;
dest.m21 = q12 - q03;
dest.m22 = 1.0f - q11 - q00;
dest.m30 = 0.0f;
dest.m31 = 0.0f;
dest.m32 = 0.0f;
dest.m33 = 1.0f;
```

The correction is that you have to swap the operators `-` and `+` between operands for `m01` `m02` `m10` `m12` `m20` `m21` according to the LHS matrix formula found here: https://en.wikipedia.org/wiki/Rotation_matrix#Quaternion

I will probably make a PR soon.

**Comment by httpdigest** [comment]
This is a misunderstanding. Firstly, with rotation about an axis there is no such thing as right-handed or left-handedness. Secondly, remember that (m00, m01, m02, m03) form the first *column* of the matrix. Therefore you need to read this formula transposed when looking at Wikipedia's entry.

**Comment by sriharshachilakapati** [comment]
No, that's what I thought in the beginning too. I found this when I printed the following matrices.

```java
Matrix4f originalMatrix = new Matrix4f().rotate((float) Math.toRadians(45), 1, 0, 0);
Matrix4f convertedMatrix = new Matrix4f().rotate(new Quaternionf(new AxisAngle4f((float) Math.toRadians(45), 1, 0, 0)));
```

And that resulted in the following output.

```java
// Original Matrix
  1.000E+0  0.000E+0  0.000E+0  0.000E+0
  0.000E+0  7.071E-1 -7.071E-1  0.000E+0
  0.000E+0  7.071E-1  7.071E-1  0.000E+0
  0.000E+0  0.000E+0  0.000E+0  1.000E+0

// Converted Matrix
  1.000E+0  0.000E+0  0.000E+0  0.000E+0
  0.000E+0  1.000E+0  0.000E+0  0.000E+0
  0.000E+0  0.000E+0  1.000E+0  0.000E+0
  0.000E+0  0.000E+0  0.000E+0  1.000E+0
```

There is something seriously wrong in the matrix rotation with quaternion. The converted matrix is always identity, and this got me in doubt.

**Comment by httpdigest** [comment]
Thanks for the find! The Quaternion(AxisAngle4f) constructor had an issue. Fixed now.

**Comment by httpdigest** [comment]
As an info: There is also a slightly shorter way of rotating about the x-axis with a Quaternion:
`Matrix4f convertedMatrix = new Matrix4f().rotate(new Quaternionf().rotateX((float) Math.toRadians(45)));`
If you also just want to rotate about the x-axis, you can do it like this:
`Matrix4f convertedMatrix = new Matrix4f().rotateX((float) Math.toRadians(45));`

**Comment by httpdigest** [comment]
Can you confirm that this issue is resolved now, with having diverted from being an issue with `Quaternionf.get(Matrix4)` to actually being an issue with `Quaternionf(AxisAngle4f)`?

**Comment by sriharshachilakapati** [comment]
Yes, this is now working. We can close the issue now.
