### ISSUE TITLE
GWT Support?

### ISSUE THREAD

**Issue by sriharshachilakapati** [JOML-CI/JOML#45]
Right now, I'm thinking of having GWT support in JOML, I'm working on a WebGL wrapper ([WebGL4J](https://github.com/sriharshachilakapati/WebGL4J/issues/2)) for GWT and would like to have some support on integrating JOML with it. I think that is possible by adding a source JAR export, and a simple `joml.gwt.xml` file that defines the GWT module (Not used in non GWT apps).

Do you think we can add a new variation of this library?

**Comment by httpdigest** [comment]
Sounds like a good idea!
Could you provide a PR on the new `gwt` branch I just created (based on `master`)?
A sources jar is automatically built during the `package` lifecycle step when building with Maven.
If you need a sources jar only, then you can also do `mvn source:jar`.

**Comment by httpdigest** [comment]
Does GWT really need both the compiled .class files and the .java source files? Or would it suffice if only the .java source files are included in the jar?

**Comment by sriharshachilakapati** [comment]
Thanks for accepting the idea. I will be cloning the repo right now, and start working on the module file. As per the jar, GWT requires both the compiled classes and the sources to be present in the classpath as it translates the source. I think I prefer to have a separate **joml-gwt** jar file.

**Comment by httpdigest** [comment]
Wow, that was a quick answer. :)

**Comment by httpdigest** [comment]
Okay, to have a separate joml-gwt file being produced, please use a new artifactId `joml-gwt` and add the following into the `<build>` element of the pom.xml:
```
  <resources>
    <resource>
      <directory>src/main/resources</directory>
    </resource>
    <resource>
      <directory>src/main/java</directory>
      <includes>
        <include>**/*.java</include>
        <include>**/*.gwt.xml</include>
      </includes>
    </resource>
  </resources>
```
That should result in a `joml-gwt.jar` being built with the class and java files as well as the gwt xml file inside it.

**Comment by sriharshachilakapati** [comment]
Thanks for helping with the POM, never actually worked with maven before. Will notify you with any progress once I start working on the code. I think I need to change some things, as NIO buffers are not supported by GWT. Do you think we can get the data into an array instead that is column major?

**Comment by httpdigest** [comment]
> Do you think we can get the data into an array instead that is column major?

Yes, definitely. Only the Matrix4 classes currently support that. It would be good to have support for float and double array get/set methods in other classes, too.

**Comment by sriharshachilakapati** [comment]
Right I will add them then. One more small question, can I create a new joml-gwt project (depending on the core) so that I can emulate the ByteBuffer and FloatBuffer classes just like LibGDX does? Sorry for asking too many questions.

**Comment by httpdigest** [comment]
Okay, I just modified the pom.xml as described above. Now, everything should be ready for you to add the get/set methods with arrays, remove the get/set methods with NIO buffers and add a gwt.xml file.

**Comment by sriharshachilakapati** [comment]
I've got this working with GWT after some large modifications to the library. See [this PR](https://github.com/JOML-CI/JOML/pull/46) on that.

![Proof that it works](http://i.imgur.com/hVBoQys.png)

**Comment by httpdigest** [comment]
Hi Sri,
just wanted to know how things are going with a gwt port of JOML?
Cheers,
Kai

**Comment by sriharshachilakapati** [comment]
Not quite good, the soon I finish making changes, you make a new commit again. Will do this once you assure me that you give me some time to do. Maybe after this LD?

**Comment by sriharshachilakapati** [comment]
And more, regarding the formatting thing, I can't find the option to leave the trailing whitespace in javadocs in IntelliJ idea. That is the major drawback, it's stripping the whitespace at the end on file save. I'll take a look at that again. Just wanted to let you know.

**Comment by httpdigest** [comment]
> Not quite good, the soon I finish making changes, you make a new commit again. Will do this once you assure me that you give me some time to do. Maybe after this LD?

You don't have to stay in sync with upstream/gwt for your changes. Just use the current state of the gwt branch (I did not change anything for two weeks in that branch and will not make any changes).
Of course, I will continue to make changes to master and the other branches.
But leave the sync'ing of your changes to me once you are finished.

**Comment by sriharshachilakapati** [comment]
Thanks for that, I will finish my changes in three days, that is, one day after LD this time. The formatting thing is bugging me still, I have disabled the remove spaces on save, but it is removing them for each method if I edit it's Javadoc automatically.

**Comment by httpdigest** [comment]
> And more, regarding the formatting thing, I can't find the option to leave the trailing whitespace in javadocs in IntelliJ idea. That is the major drawback, it's stripping the whitespace at the end on file save.

Really, I have no idea what you've done to your IDEA installation. :) I just installed a fresh copy of 14.1.4 community, created a new project from existing JOML sources, then editing some Java code and JavaDocs here and there and it won't change anything else. It even added the single whitespace character on each new empty line I added to a JavaDocs comment.

**Comment by sriharshachilakapati** [comment]
I never changed any options there, all I have is a ultimate edition, and it's behaving like that. I will look at that soon today and tomorrow. I try to not remove any such existing spaces, and also not to create any ones that are not present.
