### ISSUE TITLE
Error in setEulerAnglesXYZ from Quaternionf

### ISSUE THREAD

**Issue by bardackx** [JOML-CI/JOML#48]
Currently is rotating around the wrong axis and causing a reflection, the error is at the end of the method

x = cx * cycz + sx * sysz;
y = sx * cycz - cx * sysz;
z = cx * sycz + sx * cysz;
w = cx * cysz - sx * sycz;

should be

w = cx * cycz + sx * sysz;
x = sx * cycz - cx * sysz;
y = cx * sycz + sx * cysz;
z = cx * cysz - sx * sycz;

Maybe it the same error exists in Quaterniond ot in setEulerAngles ZYX, but I didn´t use those.

**Comment by httpdigest** [comment]
You are absolutely right! Thanks for finding and reporting. :)

**Comment by httpdigest** [comment]
The issue has been fixed now in the relevant branches of JOML, and the 1.4.1-SNAPSHOT version is available at the snapshot repository of oss.sonatype.org.
