### ISSUE TITLE
Theese features could be useful

### ISSUE THREAD

**Issue by bardackx** [JOML-CI/JOML#49]
I am changing my application code from using my custom library to use JOML instead since they both have very similar design desitions and I think theese simple functions could be useful:

Adding a scaled Vector3f to another Vector3f
Adding a scaled Vector4f to another Vector4f

Here is an example of their usage in my game —force, linearAcceleration, velocity, position, t and inverseMass are a floats

// linear integration
linearAcceleration.add(force, inverseMass);
velocity.add(linearAcceleration, t);
position.add(velocity, t);

That is equivalent to

// linear integration
linearAcceleration.x += force.x * inverseMass;
linearAcceleration.y += force.y * inverseMass;
linearAcceleration.z += force.z * inverseMass;
velocity.x += linearAcceleration.x * t;
velocity.y += linearAcceleration.y * t;
velocity.z += linearAcceleration.z * t;
position.x += velocity.x * t;
position.y += velocity.y * t;
position.z += velocity.z * t;

**Comment by httpdigest** [comment]
There is already the possibility to add a scaled vector to another vector - both scalar scaling factor as well as component-wise factor.
See [this method](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Vector3f.java#L543) as well as [this method](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Vector3f.java#L559).
