### ISSUE TITLE
Add javax.vecmath migration guide

### ISSUE THREAD

**Issue by httpdigest** [JOML-CI/JOML#5]
Add an article to the Wiki explaining how to translate from javax.vecmath classes to JOML.

**Comment by gouessej** [comment]
Reminder: vecmath is still actively maintained: https://github.com/hharrison/vecmath

**Comment by httpdigest** [comment]
Hm... this project looks rather dead to me. Last commit from exactly two years ago and no response to the one-and-only open issue. But I will email Mr. Harrison to find out.
Thanks for the info about that project!

**Comment by gouessej** [comment]
This library is mature and this project is used by default in Java3D 1.6.0, this is what I meant, sorry for the lack of accuracy. As the public API is frozen, the request for enhancement you're talking about can't be accepted and that's probably why @hharrison didn't reply to this open issue.

**Comment by gouessej** [comment]
The original implementation (from Oracle) of javax.vecmath hasn't been modified since about 2009.

**Comment by immortius** [comment]
Some details I learned from using javax.vecmath - it is included in OSX distributions of Java as an extension, and in a sealed jar. Meaning you cannot even use updated forks of the library in apps, because the apps won't run under OSX.

**Comment by gouessej** [comment]
@immortius The extension mechanism has been removed from Java 1.9, this version of Vecmath isn't picked by OpenJDK and Oracle Java and it's possible to skip all extensions by using the property "java.ext.dirs". You can use the updated versions of vecmath as long as we disable the extension mechanism or if your JVM ignores it. Java3D 1.6.0 pre 12 works correctly under Mac OS X 10.10 and it uses JogAmp's fork of Vecmath.

**Comment by httpdigest** [comment]
I am closing this now, since I feel that the need for such a migration guide is not strong enough.

**Comment by i-make-robots** [comment]
Came here from Google, looking for the migration guide.  Oh well.
