### ISSUE TITLE
Using JOML with Gradle

### ISSUE THREAD

**Issue by ShadowLordAlpha** [JOML-CI/JOML#53]
Because JOML uses maven central and sonatype is easy to use gradle with it now so it might be a good idea to have the information on how to use it with gradle in the wiki or readme pages.

The whole thing looks like this when only using JOML as an extra dependency using the latest version of JOML
```
repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

project.ext.jomlVersion = "+" 

dependencies {
    compile "org.joml:joml:${jomlVersion}"
}

```

i probably left something out so ask or tell me if there is

**Comment by httpdigest** [comment]
Thanks for this!
Added it to the main wiki page: https://github.com/JOML-CI/JOML/wiki

**Comment by ShadowLordAlpha** [comment]
ok so just a few things to make it look more like the maven version you have 

`project.ext.jomlVersion = "+" ` The + can be replaced with the version to get a specific version if needed for example `project.ext.jomlVersion = "1.5.0" ` and adding in the sonatype part of the repositories also gives it access to the snapshot versions so you can use `project.ext.jomlVersion = "1.5.2-SNAPSHOT" ` as the version the + I have there will always give gradle the most recent version of JOML though so thats why its there

**Comment by httpdigest** [comment]
I was aware of the "+". It's just that Maven does not have such a thing, except the open-ended interval notation `[1.5.0,)` in Maven 3. I could use that instead.

**Comment by httpdigest** [comment]
Okay, just changed it to 1.5.0 everywhere. Usually one wants to use a fixed version of a dependency so as not to break everything should a new incompatible version sneak in. :)

**Comment by ShadowLordAlpha** [comment]
Okay I still think it should be clearer but those who know how to use gradle shouldn't now have to go digging (just looking at the maven XML file :p) now.
