### ISSUE TITLE
What about a generalized set/get row/column in the matrix classes?

### ISSUE THREAD

**Issue by bardackx** [JOML-CI/JOML#60]
Generalized getter and setter methods for matrix classes, for example

	Vector4f v4 = ...;
	Vector3f v3 = ...;

	Matrix4f m4 = ...;
	Matrix4f m3 = ...;

	float x=1, y=2, z=3, w=4, s=1;
	int index = 0;
	
	m3.setRow(index, v4); // is the equivalent of m3.setRow(index, v4.x, v4.y, v4.z)
	m3.setRow(index, v3); // is the equivalent of m3.setRow(index, v3.x, v3.y, v3.z)
	m3.setRow(index, s); // is the equivalent of m3.setRow(index, s, s, s)
	m3.setRow(index, x, y, z);
	m3.setColumn(index, v4); // is the equivalent of m3.setColumn(index, v4.x, v4.y, v4.z)
	m3.setColumn(index, v3); // is the equivalent of m3.setColumn(index, v3.x, v3.y, v3.z)
	m3.setColumn(index, s); // is the equivalent of m3.setColumn(index, s, s, s)
	m3.setColumn(index, x, y, z);

	m4.setRow(index, v4); // is the equivalent of m3.setRow(index, v4.x, v4.y, v4.z, v4.w)
	m4.setRow(index, v3); // this could be equivalent to call m4.setRow(index, v3.x, v3.y, v3.z, 1)
	m4.setRow(index, s); // is the equivalent of m4.setRow(index, s, s, s, s)
	m4.setRow(index, x, y, z, w);
	m4.setColumn(index, v4); // is the equivalent of m3.setColumn(index, v4.x, v4.y, v4.z, v4.w)
	m4.setColumn(index, v3); // this could be equivalent to call m4.setColumn(index, v3.x, v3.y, v3.z, 1)
	m4.setColumn(index, s); // is the equivalent of m4.setColumn(index, s, s, s)
	m4.setColumn(index, x, y, z);

the implementation could look like this

	public void setRow(int row, float x, float y, float z) {
		switch (row) {
		case 0:
			m00 = x;
			m10 = y;
			m20 = z;
			break;
		case 1:
			m01 = x;
			m11 = y;
			m21 = z;
			break;
		case 2:
			m02 = x;
			m12 = y;
			m22 = z;
			break;
		default:
			throw new IndexOutOfBoundsException();
		}
	}

and this

	public void setColumn(int row, float x, float y, float z) {
		switch (row) {
		case 0:
			m00 = x;
			m01 = y;
			m02 = z;
			break;
		case 1:
			m10 = x;
			m11 = y;
			m11 = z;
			break;
		case 2:
			m20 = x;
			m21 = y;
			m22 = z;
			break;
		default:
			throw new IndexOutOfBoundsException();
		}
	}
	
I understand that Matrix4f have getColumn and getRow at this time, but they accept Vector4f only, adding support for Vector3f could be useful if we discard the w element (sometimes we only need the rotation axes for example).

**Comment by httpdigest** [comment]
Having setColumn and setRow methods with primitive arguments in addition to the vector arguments is a good idea. If you like, you can implement them and do a pull request against `master`.
I would however prefer having the full width of arguments (x, y, z, w) for 4-component vectors in those methods, because omitting the 'w' argument (either as not having it as primitive parameter or when using a Vector3 as argument) would leave the user unclear as to what happens with that 'w' component (will it be set to a default of 0.0 or 1.0, neither of which is good/desired in all cases; or will it be left unchanged), which must then be specified in the JavaDocs.
And IMHO It is also not a burden for the client to additionally specify the 'w' argument.

**Comment by bardackx** [comment]
I have the code ready, but I'm very new at using github for other than code browsing, how can I send my code?

the api looks like this

	float[] array = new float[4];
	Matrix4f mat4f = new Matrix4f();
	Matrix3f mat3f = new Matrix3f();
	Vector4f vec4f = new Vector4f();
	Vector3f vec3f = new Vector3f();
	Vector2f vec2f = new Vector2f();
	float x = 1, y = 1, z = 1, w = 1;
	int row = 0, column = 0, n = 0;

	// MAT4
	mat4f.getRow(row, vec4f); // .............. ---
	mat4f.getRow(row, vec3f); // .............. new
	
	mat4f.setRow(row, vec4f); // .............. new
	mat4f.setRow(row, vec3f); // .............. new
	mat4f.setRow(row, vec3f, 1f); // .......... new
	mat4f.setRow(row, x, y, z, w); // ......... new
	mat4f.setRow(row, x, y, z); // ............ new
	mat4f.setRow(row, array, 0, n); // ........ new
	mat4f.setRow(row, array); // .............. new

	mat4f.getColumn(column, vec4f); // ........ ---
	mat4f.getColumn(column, vec3f); // ........ new
	
	mat4f.setColumn(column, vec4f); // ........ new
	mat4f.setColumn(column, vec3f); // ........ new
	mat4f.setColumn(column, vec3f, 1f); // .... new
	mat4f.setColumn(column, x, y, z, w); // ... new
	mat4f.setColumn(column, x, y, z); // ...... new
	mat4f.setColumn(column, array, 0, n); // .. new
	mat4f.setColumn(column, array); // ........ new

	// MAT3
	mat3f.getRow(row, vec3f); // .............. ---
	mat3f.getRow(row, vec2f); // .............. new
	
	mat3f.setRow(row, vec3f); // .............. new
	mat3f.setRow(row, vec2f); // .............. new
	mat3f.setRow(row, vec2f, 1f); // .......... new
	mat3f.setRow(row, x, y, z); // ............ new
	mat3f.setRow(row, x, y); // ............... new
	mat3f.setRow(row, array, 0, n); // ........ new
	mat3f.setRow(row, array); // .............. new

	mat3f.getColumn(column, vec3f); // ........ ---
	mat3f.getColumn(column, vec2f); // ........ new
	
	mat3f.setColumn(column, vec3f); // ........ new
	mat3f.setColumn(column, vec2f); // ........ new
	mat3f.setColumn(column, vec2f, 1f); // .... new
	mat3f.setColumn(column, x, y, z); // ...... new
	mat3f.setColumn(column, x, y); // ......... new
	mat3f.setColumn(column, array, 0, n); // .. new
	mat3f.setColumn(column, array); // ........ new

I played with the idea of doing the same for Quaternionf, but I'm not sure
	
	// QUAT
	// I am not sure about the namings here
	// Quaternionf quatf = new Quaternionf();
	// quatf.setComponents(vec4f); // ............ new
	// quatf.setComponents(vec3f, w); // ......... new
	// quatf.setComplexComponents(vec3f); // ..... new
	// quatf.getComponents(vec4f); // ............ new
	// quatf.getComplexComponents(vec3f); // ..... new
	// quatf.getComponents(array, offset, n); // . new
	// quatf.setComponents(array, offset, n); // . new
	// quatf.getComponents(array); // ............ new
	// quatf.setComponents(array); // ............ new
	
The same with theese

	// MAT3
	// mat3f.setRows(vec3f, vec3f, vec3f); // ......... new
	// mat3f.setColumns(vec3f, vec3f, vec3f); // ...... new
	
	// MAT4
	// mat34f.setRows(vec4f, vec4f, vec4f, vec4f); // . new
	// mat4f.setColumns(vec4f, vec4f, vec4f, vec4f); // new

**Comment by httpdigest** [comment]
First, you have to have a GitHub account on your own.
Then you navigate to JOML here on GitHub and click on the button that says "Fork" at the top left of the page. Then you checkout your own repository, make your changes, commit them to your own repository and then you click on "Pull Request" (or something) in your own repository.
This way I will get a notification about you wanting to share code with JOML.

But like I said above, I would only like to add these two methods:

> mat4f.setRow(row, x, y, z, w); // ......... new
> mat4f.setColumn(column, x, y, z, w); // ... new

Everything else I see does not add any significant convenience to the already available methods. The rationale for having the new 4-primitive methods is because otherwise one would have to allocate a Vector4f to set a row/column. Using these methods this is not necessary anymore.
All other methods can be emulated using this.

**Comment by bardackx** [comment]
to make code more friendly, why not both?

for example, I havea a method that tests if two OOBB are intersecting, at the begining I get the rotation axes of each box and the halfwidths of each box

this is how it looks now

	final float[] a = new float[3], b = new float[3];
	a[0] = ((Box) bA.getShape()).getHalfSize().x;
	a[1] = ((Box) bA.getShape()).getHalfSize().y;
	a[2] = ((Box) bA.getShape()).getHalfSize().z;
	b[0] = ((Box) bB.getShape()).getHalfSize().x;
	b[1] = ((Box) bB.getShape()).getHalfSize().y;
	b[2] = ((Box) bB.getShape()).getHalfSize().z;
	final Vector3f[] A = new Vector3f[3], B = new Vector3f[3];
	A[0] = new Vector3f(bA.transform.m00, bA.transform.m01, bA.transform.m02);
	A[1] = new Vector3f(bA.transform.m10, bA.transform.m11, bA.transform.m12);
	A[2] = new Vector3f(bA.transform.m20, bA.transform.m21, bA.transform.m22);
	B[0] = new Vector3f(bB.transform.m00, bB.transform.m01, bB.transform.m02);
	B[1] = new Vector3f(bB.transform.m10, bB.transform.m11, bB.transform.m12);
	B[2] = new Vector3f(bB.transform.m20, bB.transform.m21, bB.transform.m22);
	
this is how it could look

	final float[] a = new float[3], b = new float[3];
	((Box) bA.getShape()).getHalfSize().get(a); // copy xyz to array
	((Box) bB.getShape()).getHalfSize().get(b); // copy xyz to array
	final Vector3f[] A = new Vector3f[3], B = new Vector3f[3];
	for (int i = 0; i < 3; i++) {
		A[i] = bA.transform.getColumn(i, new Vector3f()); // get3f from mat4f top-right 3x3 matrix
		B[i] = bB.transform.getColumn(i, new Vector3f()); // get3f from mat4f top-right 3x3 matrix
	}

theese method could make the client code easier to read

**Comment by httpdigest** [comment]
I am assuming you have to copy a vector into a float array because of a third-party library which does the computation on float arrays? If not, then why are you converting the vectors to float arrays, and not just perform the OOB computation on vectors?

> to make code more friendly, why not both?

What do you mean with *both*? Both what?

> Why not?

Because it horrendously bloats the API. I do not like 200 overloads (exaggerated) of such a simple method as getRow() and getColumn().

**Comment by ShadowLordAlpha** [comment]
What about using a ByteBuffee then instead of a vector? It would allow both an array and vector as arrays are easy to wrap and JOML already provides support to write a vector to a bytebuffer.

**Comment by bardackx** [comment]
Oh, for the sake of simplicity, I get it;

With both I meant, both (float, float, float, float) and (Vector3f, float).

The reason fot the arrays is because I need to iterate through the axes in different steps, and multiply for the length of the box in that axis, for the radius projection in the SAT algorithm.

The buffer option sounds good too.
