### ISSUE TITLE
Speeding up the calculations with lookup tables (+ other simplifications)

### ISSUE THREAD

**Issue by exigow** [JOML-CI/JOML#62]
Hey,

have you ever thought about speeding up the calculation functions such as sine or atan2 using lookup tables or some cool hacks/simplifications? Calculations may be much faster at the expense of accuracy (which is practically invisible) AND you can avoid frequent casting to float (because the java-math that uses doubles everywhere :( ). 

These techniques work well in libraries like libGDX (MathUtils class).

**Comment by httpdigest** [comment]
Hi,
yes. There has been very intensive discussions and thorough evaluations of possible algorithms on java-gaming.org about this, and some members there have built impressive and flexibly tunable solutions to balance speed vs. accuracy.
I'll ask them for permission to have the best algorithms included in JOML, and create a new `Math` class as drop-in replacement for `java.lang.Math`.
Important properties of the algorithm will likely be configurable via system properties.
Stay tuned! :)

**Comment by exigow** [comment]
Very cool. Thanks for fast response.
You mean this discussion: http://www.java-gaming.org/index.php?topic=36469.0 ???

**Comment by httpdigest** [comment]
Yes, that's the one. And I have now permission from 'Riven' to inckude his algorithm in JOML.
I find this one the best.
Will write here when it's done.

**Comment by httpdigest** [comment]
Hi Jakub, I created a new branch https://github.com/JOML-CI/JOML/tree/fastmath with a new class `Math` containing configurable approximations of sin/cos.
The current algorithms is a simple lookup table, whose size can be configured via the system property `org.joml.Math.sinLookupTableBits`. The default is 12 bits, meaning 4096 different cached values.
