### ISSUE TITLE
'set' variants of 'rotate' methods.

### ISSUE THREAD

**Issue by dustContributor** [JOML-CI/JOML#65]
Hi! It seems 'rotate' functions dont have a 'set' variant like other methods (setPerspective, setLookAt, setTranslation, etc). They all multiply the existing matrix.

I'm mostly interested in a 'set' variant for 'rotateXYZ' mostly, but I see there are other variations.

**Comment by dustContributor** [comment]
NVM I just noticed the 'rotation' methods.

**Comment by dustContributor** [comment]
Actually I *can* make use of a 'setRotationXYZ' variant that only sets the rotation related components (ie, in the case of setRotationXYZ, it would leave translation untouched).

**Comment by httpdigest** [comment]
The setRotationXYZ/ZYX/YXZ methods are in now.

**Comment by dustContributor** [comment]
Sweet, thanks.
