### ISSUE TITLE
"safe" normalize variant for vectors.

### ISSUE THREAD

**Issue by dustContributor** [JOML-CI/JOML#66]
Hi! I have no immediate need for this but it might come in handy for some people:

```java
public final Vector3f safeNormalize() // Or 'normalizeSafe'
{
  final float sqrdLen = lengthSquared();
  // If length is zero, normalize would produce NaNs.
  // If it is 1.0, then its not necessary to normalize.
  if ( sqrdLen != 0.0f && sqrdLen != 1.0f )
  {
    final float invLen = 1.0f / Math.sqrt(sqrdLen);
    this.x *= invLen;
    this.y *= invLen;
    this.z *= invLen;
  }
  return this;
}
```

**Comment by httpdigest** [comment]
Sorry for not responding to this issue for so long, but *normalizing* a vector must normalize that vector. If the input is a null vector, the result must logically be +/-infinity. Generating a special floating point value such as infinity in this case (not NaN) also helps the user to identify bugs in her/his code.

**Comment by dustContributor** [comment]
Yeah, that's why I propose a different method altogether, this doesn't replaces normalize. You'd use safeNormalize only when you want to avoid NaNs at all costs. That should be mentioned in the doc.
