### ISSUE TITLE
JAR files

### ISSUE THREAD

**Issue by nickdbush** [JOML-CI/JOML#67]
Do you think we could have the .jar files back on  the releases please? It would be great to just drop it into the project!

**Comment by httpdigest** [comment]
If you cannot build yourself then you can always download it release version from [Maven Central](https://repo.maven.apache.org/maven2/org/joml/joml/) or snapshot versions from [oss.sonatype.org](https://oss.sonatype.org/#nexus-search;quick~joml).
I highly encourage you to use a dependency management system like Maven or Gradle with your projects, which will download those artifacts automatically for you. :)

**Comment by nickdbush** [comment]
Right, yes. My bad, didn't see your message on the 1.3.5 release about that!
