### ISSUE TITLE
Bug in maxComponent on Vector3f /3d

### ISSUE THREAD

**Issue by lars-larsen** [JOML-CI/JOML#69]
The maxComponent method of the Vector class has an implementation error. 

maxComponent on a vector like Vector(3,1,2) will return  2.

if (xy && yz) {   // false, because 1 < 2
    return 0;
} else if (yz) {  // false, because 1 < 2
    return 1;
}
return 2;

BTW: A minComponent would be great too.

**Comment by httpdigest** [comment]
Oops.. sorry. Thanks for reporting! It should of course be
`(x > y && x > z)` in the first condition.
Will fix it soon and add the requested minComponent.

**Comment by httpdigest** [comment]
With https://github.com/JOML-CI/JOML/commit/1f5e29b28b14a94b87b8d4e71c8fbe66f06dbf12 it's in 1.6.7-SNAPSHOT now.
