### ISSUE TITLE
Rotation() result divergence

### ISSUE THREAD

**Issue by elect86** [JOML-CI/JOML#75]
`Matrix4f.rotation(1f, 10f, 0f, 0f)` returns `m00 = 46.51007`. `glm` returns instead `m00 == 1`

probabily because a normalization is missing

**Comment by httpdigest** [comment]
Why does not anyone read the JavaDocs... I put about 99.9% of the effort in writing documentation and not Java code. ;)
That JavaDoc clearly says:
**The axis described by the three components needs to be a unit vector.**

**Comment by chriscamacho** [comment]
I'm surprised, your surprised people don't read docs.... ;)

**Comment by elect86** [comment]
I gave a try normalizing it before but I got a wrong result anyway, I will double check

**Comment by httpdigest** [comment]
Doing:
```Java
Matrix4f m = new Matrix4f();
m.rotation(1, 1, 0, 0); // <- rotate 1 radians (approx. 57 degrees) about the x axis
System.err.println(m);
```
gave:
```
  1,000E+0  0,000E+0  0,000E+0  0,000E+0
  0,000E+0  5,403E-1 -8,415E-1  0,000E+0
  0,000E+0  8,415E-1  5,403E-1  0,000E+0
  0,000E+0  0,000E+0  0,000E+0  1,000E+0
```
which is correct and should be what GLM outputs.

**Comment by elect86** [comment]
Yep, I already tried that and was the same.

Anyway it turned out it was indeed the normalization..

My bad, sorry for the bother

**Comment by httpdigest** [comment]
Alright, cool. It's okay, keep bothering if you have trouble with anything else. :)

**Comment by elect86** [comment]
You may want to add a matrix3f.normal()

**Comment by httpdigest** [comment]
No, I don't. Because [it is already there](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/Matrix3f.java#L2411). :)

**Comment by elect86** [comment]
Yep

**Comment by httpdigest** [comment]
Added with https://github.com/JOML-CI/JOML/commit/970dc6a5601c251482c53609b0a1726f9a6d994b
