### ISSUE TITLE
Add support for Trapezoidal Shadow Maps

### ISSUE THREAD

**Issue by httpdigest** [JOML-CI/JOML#80]
JOML can aid with TSM by providing a function which transforms the camera frustum trapezoid as seen by a light source into a unit cube.

References:
- http://www.comp.nus.edu.sg/~tants/tsm.html
- http://www.comp.nus.edu.sg/~tants/tsm/TSM_recipe.html
- https://kenai.com/downloads/wpbdc/Documents/tsm.pdf

**Comment by dustContributor** [comment]
Makes more sense to leave it here, seems like this method is patent encumbered:

> * This work has a patent filed by our University. However, it is not our intention to derive much monetary rewards from the patent. Most of all, universities are generally non-profit organizations and reputation/recognition (of creating useful techniques) rather than money is utmost important to them; our University is no exception in this case. Do feel free to explore TSM. Should you have further questions or problems about the technique, just drop us an email - we do our best in giving support. **If you are interested in using it for commercial products, we would be happy to listen to you, and then work with you to obtain the right to use with little hassle and at most a small token of appreciation of some form from you.**

**Comment by httpdigest** [comment]
So what's the big deal? There are plenty of references in the source code (so I'm not claiming of having invented that) and if someone actually thinks about using JOML in a commercial product and happens to use that implementation then they can just drop off an email to the TSM authors saying how wonderful their invention is and that it is going to be mentioned in some text of ones application and then they'll likely just say:
"Okay, thanks for giving us credit, go ahead. Also it's now 12 years since and we've gone our separate ways and really don't care anymore about it."
However, I find it a bit amusing that a non-profit organization issues a patent on something that they will not make money with. Patents are there to guarantee the inventor the sole right to _make money_ by selling/licensing that invention.
So, it's just all about giving credit where credit is due.

**Comment by dustContributor** [comment]
"a small token of appreciation of some form from you" to me that sounds like money. The university owns the patent, not those people. Have you dealt with university bureaucracy? It'll be anything but a simple email and a "Thanks to..." note.

Of course, do as you wish. I'm just pointing it out since it wasn't directly mentioned.

**Comment by httpdigest** [comment]
I just contacted the authors about that topic and if they are not affiliated anymore with that topic, if they could maybe delegate me to some representative of that University in Singapore.
Let's see how things turn out. :)

**Comment by dustContributor** [comment]
Its on! :stuck_out_tongue_closed_eyes:

**Comment by httpdigest** [comment]
For the records, here is the email response I got from Tan Tiow Seng today:
> Hi Kai,
> 
> For commercial use, the university would like to be paid for a small token sum, and be acknowledged somewhere in the final products.
> 
> Regards
> Tiow Seng
So, it indeed seems like for commercial uses this algorithm should be avoided. :)

**Comment by kappaOne** [comment]
One thing to keep in mind is that patents last for a maximum of 20 years from the date of filing, [this one in particular](http://www.google.com/patents/US20070040832) seems to have been filed in 2004, therefore will be valid for another 6 years until 2024, after which it should be free to use.

**Comment by dustContributor** [comment]
Figured as much. Patents are a minefield in this kind the thing and something to watch out for.

For example, its the reason marching cubes started to being used recently only, or like Carmack's Reverse, which was actually patented by Creative before so Id Software had to make a deal to include EAX in Doom 3 in exchange for using the method.

For gamedevs its kinda of a unspoken rule that you shouldn't patent your stuff, but there are always exceptions. Quite a few of the cool methods shown in SIGGRAPH can't be used freely for similar concerns.

**Comment by httpdigest** [comment]
Thanks @kappaOne for the info about the lifetime. It's good new though, that people can build non-commercial games and work on soon-to-be commercial games for the next 6 years to release them then. :)
