### ISSUE TITLE
Provide SSE-optimized JNI functions

### ISSUE THREAD

**Issue by httpdigest** [JOML-CI/JOML#81]
Previously, I did some testing on doing matrix calculations in native functions via SSE/AVX instructions: https://github.com/JOML-CI/JOML/issues/30

That turned out to be slower than the calculations with standard scalar arithmetic operations in Java. This was due to the approach of "batching" all operations. In order for that batching to work, the operands to each method invocations as well as the opcodes of each operation had to be stored in native memory for the native function to decode/read and execute. That storing and reading of the opcodes and operands was the major bottleneck.

Now, there is another more promising approach: Not batching the operations but simply directly calling a JNI function to do the job with optimized SSE instructions. Initial testing showed major performance increases. See the JMH results below:

```
joml-array (using a float[16]):

Benchmark                             Mode  Cnt          Score         Error  Units
Matrix4fBenchmarks.testInvert        thrpt    3   24760865,260 ±  910609,284  ops/s
Matrix4fBenchmarks.testMul           thrpt    3   34555251,163 ±  183270,652  ops/s
Matrix4fBenchmarks.testMulAffine     thrpt    3   52189265,415 ±  622020,725  ops/s

joml-jni (using native memory and JNI functions):

Benchmark                             Mode  Cnt          Score          Error  Units
Matrix4fBenchmarks.testInvert        thrpt    3   36367075,182 ±   283999,981  ops/s
Matrix4fBenchmarks.testMul           thrpt    3   70239126,361 ±    27891,033  ops/s
Matrix4fBenchmarks.testMulAffine     thrpt    3   76090662,949 ±   342632,179  ops/s
```

Work on intrinsifying all heavy/important JOML methods has started in the [jni](https://github.com/JOML-CI/JOML/tree/jni) branch based off the [array](https://github.com/JOML-CI/JOML/tree/array) branch.

**Comment by dustContributor** [comment]
How does it compare with normal (non-array, all in Java) JOML functions?

**Comment by httpdigest** [comment]
Here are some benchmark results on an i7 with JDK1.8.0_92:
```
Benchmark                            Mode  Cnt   Score   Error  Units
Matrix4fBenchmarks.CopyPojo          avgt    5   8,356 ± 0,741  ns/op
Matrix4fBenchmarks.CopyUnsafe        avgt    5   7,326 ± 0,605  ns/op
Matrix4fBenchmarks.IdentityPojo      avgt    5   6,138 ± 0,840  ns/op
Matrix4fBenchmarks.IdentityUnsafe    avgt    5   5,637 ± 0,613  ns/op
Matrix4fBenchmarks.InvertAVX         avgt    5  22,756 ± 3,017  ns/op
Matrix4fBenchmarks.InvertAffinePojo  avgt    5  22,754 ± 1,666  ns/op
Matrix4fBenchmarks.InvertPojo        avgt    5  40,903 ± 9,051  ns/op
Matrix4fBenchmarks.InvertSSE         avgt    5  25,583 ± 5,732  ns/op
Matrix4fBenchmarks.MulAVX            avgt    5  15,027 ± 1,642  ns/op
Matrix4fBenchmarks.MulAffineAVX      avgt    5  11,220 ± 0,655  ns/op
Matrix4fBenchmarks.MulAffinePojo     avgt    5  16,367 ± 1,103  ns/op
Matrix4fBenchmarks.MulPojo           avgt    5  25,561 ± 2,351  ns/op
Matrix4fBenchmarks.MulSSE            avgt    5  14,497 ± 0,352  ns/op
Matrix4fBenchmarks.ZeroPojo          avgt    5   6,322 ± 0,655  ns/op
Matrix4fBenchmarks.ZeroUnsafe        avgt    5   5,185 ± 0,741  ns/op
```
POJO means the normal Matrix4f Java version with the 16 primitive float fields, Unsafe means that there was `sun.misc.Unsafe` used for faster copying, SSE means JNI function using x86 SSE-128bit, AVX means JNI function using x86 AVX1-128bit.

**Comment by dustContributor** [comment]
Nice, thanks!

**Comment by httpdigest** [comment]
Sure thing! Btw.: these are the only methods that actually benefit from native functions. For every other method the JNI overhead of 19-22 clock cycles (on a 64-bit "server" HotSpot JVM, measured with RDTSC instruction and empty JNI function) is just too high, resulting in the pure Java version to be faster. If it wasn't for JNIs overhead, hand-written SIMD native code would outrun _every_ Java method.
Waiting for project Panama...

**Comment by dustContributor** [comment]
Yeah, I asked because I've seen a few times people reimplementing their matrix functions in SSE, entirely in C++, and still performing worse than a direct implementation (turns out transitions between SSE instructions and scalar ones have a tiny penalty). Nice to see this isnt an issue here.

**Comment by httpdigest** [comment]
There is a penalty when mixing legacy-encoded SSE instructions with VEX-encoded AVX 256 bit instructions, because the former does not guarantee that the upper 128 bits of the YMM registers are zeroed after legacy-encoded SSE instructions are finished with them and before used by AVX instructions. So when the CPU encounters legacy non-VEX-encoded SSE instructions and afterwards an AVX-256 VEX-encoded instruction, it must perform a costly transition to zero out the upper 128 bits.
This is probably what you meant.
See: [this Intel paper](https://software.intel.com/sites/default/files/m/d/4/1/d/8/11MC12_Avoiding_2BAVX-SSE_2BTransition_2BPenalties_2Brh_2Bfinal.pdf)
However, there is a simple and cheap workaround: VZEROUPPER.
Or just compile the code that uses SSE instructions with the new VEX-encoding. In GCC this can be done by specifying "-mavx" and on msvc this is /arch:avx.

**Comment by dustContributor** [comment]
Yeah, I remember that paper. I think it was [this also](http://stackoverflow.com/questions/8847429/sse-slower-than-fpu/8847451#8847451):

Although I can't seem to find a nicer source on that one anyway : / 

Have you seen Agner's manuals? http://www.agner.org/optimize/ Like ["Optimizing subroutines in assembly language"](http://www.agner.org/optimize/optimizing_assembly.pdf) for example. Interesting stuff.

**Comment by dustContributor** [comment]
I have one question, have you tried bulk methods for some of the operations?

Like Matrix4.bulkMul(lefta, righta, leftb, rightb, resulta, resultb), that would do:

resulta = lefta * righta;
resultb = leftb * rightb;

ie, something that does two (or more) matrix operations in one go. Or various vector dots/cross in one go (for vectors you'd probably need a bunch to offset the overhead).

**Comment by httpdigest** [comment]
Yes, there are batch matrix multiplication methods. See:
- https://github.com/JOML-CI/JOML/blob/jni/native/src/org_joml_Matrix4f.c#L144
- https://github.com/JOML-CI/JOML/blob/jni/src/org/joml/Matrix4f.java#L233

**Comment by httpdigest** [comment]
Closing this for now. Can be reopened once the JVM provides ways to execute native instructions without the 20-cycles-overhead of JNI which renders most SSE-optimized functions rather useless/suboptimal.
The cost (all other methods being around 10% slower when using native memory accesses compared to direct field accesses) currently is higher than the gain (which is just faster matrix.mul() and invert()).
