### ISSUE TITLE
Using rotateTo with parallel axes returns a Quaternion with NaN for w,x,y,z

### ISSUE THREAD

**Issue by sanjay900** [JOML-CI/JOML#82]
In the code im currently using, i end up checking for NaN and then generating a 180 degree rotation around an axis using this code:
```java
if (Double.isNaN(q.w)) {
    Vector3d axis = new Vector3d(0,1,0).cross(v0);
    if (axis.lengthSquared() == 0) { // pick another axis if colinear
        axis = new Vector3d(1,0,0).cross(v0);
    }
    axis.normalize();
    q = q.fromAxisAngleRad(axis,Math.PI);
}
```
I based it around this: https://bitbucket.org/sinbad/ogre/src/9db75e3ba05c/OgreMain/include/OgreVector3.h?fileviewer=file-view-default#cl-651 
Is there a better way to do this?

**Comment by httpdigest** [comment]
Thanks for reporting this issue!
The general problem is that with parallel but opposing 'to' and 'from' vectors, there are an infinite number of shortest arc rotations possible. The commit https://github.com/JOML-CI/JOML/commit/0d9848cc451466a403af0008f5b4f96f5aae0f28 fixes this by simply using the x axis as the rotation axis. This should not be an issue unless you want to interpolate the rotation and wish to use a different axis.
That commit has been merged into `master` too.

**Comment by sanjay900** [comment]
Seems to work well, thanks!
