### ISSUE TITLE
Floats order in input/output of matrixes

### ISSUE THREAD

**Issue by antain** [JOML-CI/JOML#87]
Hello.

The order in which matrixes receives / writes floats is column by column.

When you write code like this:
```
Matrix4f matrix4f = new Matrix4f(
		0.0F, 1.0F, 2.0F, 3.0F, // <- column 1 (m00, m10, m20, m30)
		0.1F, 1.1F, 2.1F, 3.1F, // <- column 2
		0.2F, 1.2F, 2.2F, 3.2F, // <- column 3
		0.3F, 1.3F, 2.3F, 3.3F  // <- column 4
);
System.out.println(matrix4f.toString());
```
without comments you won't expect output:
```
  0,000E+0  1,000E-1  2,000E-1  3,000E-1
  1,000E+0  1,100E+0  1,200E+0  1,300E+0
  2,000E+0  2,100E+0  2,200E+0  2,300E+0
  3,000E+0  3,100E+0  3,200E+0  3,300E+0
```

Also the input format of opengl is row by row, so buffer created via get method of matrix won't fit it.

So maybe better add overloading methods with flag/enum, to accept/output floats row by row or column by column.
Or at least add to all methods which works with something array-like that order is column by column.

**Comment by httpdigest** [comment]
> Also the input format of opengl is row by row

This is wrong. The correct term of what you might be referring to is **row-major**. OpenGL, however, expects **column-major**. Just like all get() methods of the matrix classes write out.

About the float primitives constructor: I honestly didn't expect anyone to use these constructors :) , as that would likely require to do computations which the matrix class includes itself. So, you would not use this constructor to build a projection matrix or a lookat matrix. You would use the heavily optimized Matrix4f methods.
If you read the matrix values from some external source and want to build a JOML Matrix4f out of them, then I suggest having a look at the set() methods, which work with arrays and NIO buffers.

**Comment by antain** [comment]
> This is wrong. The correct term of what you might be referring to is row-major. OpenGL, however, expects column-major. Just like all get() methods of the matrix classes write out.

Yeah, my bad. Misread docs. Sorry.

And about constructor. I start using it only to check order. :)

But regardless. Maybe still add to javadocs, that input/output are column-major?
