### ISSUE TITLE
Matrix3f

### ISSUE THREAD

**Issue by kudodev** [JOML-CI/JOML#89]
Hello. Can you add: **Matrix3f.add(Matrix3f).** I need it for my physics engine. Also it is included for Matrix4f.

**Comment by kudodev** [comment]
Also used in physics engines:
`public Matrix3f setSkewSymmetric(Vector3f v) {
        m00 = m11 = m22 = 0;
        m01 = -v.z;
        m02 = v.y;
        m10 = v.z;
        m12 = -v.x;
        m20 = -v.y;
        m21 = v.x;
        return this;
    }`

**Comment by kudodev** [comment]
Also, and thanks for the great library!:
```
public Matrix3f set(Vector3f a, Vector3f b, Vector3f c) {
    m00 = a.x;
    m01 = a.y;
    m02 = a.z;
    m10 = b.x;
    m11 = b.y;
    m12 = b.z;
    m20 = c.x;
    m21 = c.y;
    m22 = c.z;
    return this;
}
```

**Comment by kudodev** [comment]
Also:
```
public Vector3f mulTranspose(Matrix3f m) {
    set(
            m.m00 * x + m.m01 * y + m.m02 * z,
            m.m10 * x + m.m11 * y + m.m12 * z,
            m.m20 * x + m.m21 * y + m.m22 * z
    );
    return this;
}

public Vector3f mulTranspose(Matrix4f m) {
    set(
            m.m00 * x + m.m01 * y + m.m02 * z + m.m03,
            m.m10 * x + m.m11 * y + m.m12 * z + m.m13,
            m.m20 * x + m.m21 * y + m.m22 * z + m.m23
    );
    return this;
}
```

**Comment by httpdigest** [comment]
Your proposals have been added with https://github.com/JOML-CI/JOML/commit/7d98f8cdef9c517fa68b1d6475f9b8b4ec073090.
