### ISSUE TITLE
Faster cos/sin without lookup table

### ISSUE THREAD

**Issue by dustContributor** [JOML-CI/JOML#92]
This might be of some interest to you:

http://www.gamedev.net/topic/681723-faster-sin-and-cos/

**Comment by kappaOne** [comment]
There was quite an extensive topic on this subject over on [JGO](http://www.java-gaming.org/topics/extremely-fast-sine-cosine/36469/view.html). IIRC it was pretty hard to beat a good cos/sin lookup table implementation.

**Comment by httpdigest** [comment]
@dustContributor, thanks for mentioning this article!
I have to say, the accuracy of L. Spiro's implementation is fantastic. Applying about 1,000,000 small rotations to a Matrix4f only changes the length of a transformed vector by 1%. java.lang.Math.sin() does not perform better in that regard.

@kappaOne is right, though. The current lookup table algorithm as implemented in the org.joml.Math class (not compiled by default) beats L. Spiro's implementation:

JMH benchmark results (with [avoiding constant-folding](http://tutorials.jenkov.com/java-performance/jmh.html#avoiding-constant-folding) using values within -PI...+PI):
```
Benchmark     Mode  Cnt   Score   Error  Units
Bench.sin1    avgt    5  27,808 ± 0,044  ns/op
Bench.sin2    avgt    5  12,066 ± 0,020  ns/op
Bench.stdsin  avgt    5  35,658 ± 0,693  ns/op
```

Using values far outside -PI...+PI:
```
Benchmark     Mode  Cnt   Score   Error  Units
Bench.sin1    avgt    5  27,826 ± 0,079  ns/op
Bench.sin2    avgt    5  12,101 ± 0,045  ns/op
Bench.stdsin  avgt    5  56,137 ± 0,264  ns/op
```
sin1 = L. Spiro's implementation
sin2 = theagentd's JGO implementation with linear interpolation and 14 bits lookup table (to achieve the same fantastic accuracy as L. Spiro's)
stdsin = java.lang.Math.sin()

Both algorithms seem to take care of excessively large values properly.

**Comment by dustContributor** [comment]
Ah I see. Yeah, thats the kind of use case I had in mind. At least my use cases for sin/cos are sporadic enough that a lookup table seem a bit heavy handed. Anyway, thanks for looking into it.

**Comment by httpdigest** [comment]
L. Spiro's algorithm has been implemented in https://github.com/JOML-CI/JOML/commit/aed138caeba02491986543f5eb2428872023c98e and can be activated for all JOML methods that make use of sin/cos (such as Matrix[3/4].rotate\*()) via the system property `joml.fastmath`.
See the [Configuration](https://github.com/JOML-CI/JOML/wiki/Configuration) Wiki page.
