### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by J-Ibarra** [JOML-CI/JOML#94]
possible bug in the classes Intersectf and Intersectd 

int the metod

public static boolean intersectSphereSphere(Vector3f centerA, float radiusSquaredA, Vector3f centerB, float radiusSquaredB, Vector4f centerAndRadiusOfIntersectionCircle) {
        return intersectSphereSphere(centerA.x, centerA.y, centerA.z, **radiusSquaredB**, centerB.x, centerB.y, centerB.z, radiusSquaredB, centerAndRadiusOfIntersectionCircle);
    }

maybe is

public static boolean intersectSphereSphere(Vector3f centerA, float radiusSquaredA, Vector3f centerB, float radiusSquaredB, Vector4f centerAndRadiusOfIntersectionCircle) {
        return intersectSphereSphere(centerA.x, centerA.y, centerA.z, **radiusSquaredA**, centerB.x, centerB.y, centerB.z, radiusSquaredB, centerAndRadiusOfIntersectionCircle);
    }

**Comment by httpdigest** [comment]
You have probably a very old version of JOML checked out. See https://github.com/JOML-CI/JOML/pull/85, which solved this issue.
